### ISSUE TITLE
RFE: making caja gtk3 only code

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#600] opened 2016-07-24 12:43 UTC
Luke did fix https://github.com/mate-desktop/caja/issues/575 with changes for caja and m-s-d, more details see report.
Another open issue is https://github.com/mate-desktop/caja/issues/570
This affects more debian and their derivatives as i don't see that libunigue will dropped in other rpm distros.
Specially for the GtkApplcation port it seems to be easier to work on gtk3-only code.
On the other side switching caja to gtk3 is a point of no return, because than it is impossible to build a gtk2 desktop any more.
Guys, we need to fell an decision if we do that or not. Luke needs really a statement for further work.

Thank you
@monsta @flexiondotorg @clefebvre @XRevan86
thoughts?
##

**Comment by XRevan86** [comment] 2016-07-24 15:50
I'm for keeping Gtk2 support in applications like MATE Panel in the 1.16 release.
There are regressions in the Gtk3 build that aren't solved yet.

**Comment by lukefromdc** [comment] 2016-07-25 05:18
For Caja we get nasty issues with either GTK version:
GTK2: loss of Libunique and no guide to porting from Nautilus. Very comples code
GTK3: loss of noncompositing desktop background support beginning with GTK 3.21

Keep in mind the original Nautilus was the main project of an entire company (easel) that hoped to monetize it by using it as a front-end for online file storage. That never panned out but all of easel was the original team here, probably far larger than what we now have to deal with the GTK3 treadmill. Of course if we don't port to GTK3 we lose any chance of ever running over Wayland, and Debian Unstable now builds on GTK3.

Allowing builds with statically linked libraries could permit GTK2 builds of one MATE app. That would alllow things like a GTK2 build of caja for users who have issues with compositing in Marco and cannot use compiz. Without a better fix for https://github.com/mate-desktop/caja/issues/575 that works with the old Caja background help (we have gotten NO help from GNOME) we can forget the GTK3/no compositing use case in distros using GTK 3.22 when it comes out. Either the background is black(my branch) or the icons won't redraw properly(master as of 7-15-2016).  I would love to see a better fix for that crap but after six weeks of experiments the best I could do was to copy what Nautilus did. Might take having back the whole easel team to deal with this the right way.

**Comment by monsta** [comment] 2016-07-25 18:51
Should we really focus on libunique vs GtkApplication issue now?

**Comment by lukefromdc** [comment] 2016-07-25 20:33
The Libunique situation is probably the main threat to being able to keep
GTK2 builds because Debian plans to drop it. To get around that we would
need to have GTK2 compatable replacement code for every package using
Libunique. So far the merged ports of Libunique fixes have been for packages
like Engrampa that have already been migrated to GTK3-only.

**Comment by raveit65** [comment] 2016-07-26 08:14
> I'm for keeping Gtk2 support in applications like MATE Panel in the 1.16 release.
There are regressions in the Gtk3 build that aren't solved yet.

Which tons of regressions?
And does this mean you start work on them?
Or is this is simple NO?

**Comment by raveit65** [comment] 2016-07-26 08:17
> Should we really focus on libunique vs GtkApplication issue now?

Only debian and their derivatives needs this, i can live with libunique ;)

**Comment by zaps166** [comment] 2016-07-26 09:02
Don't drop GTK2 support. "New" is not always better and GTK2 is still maintained.

---

GTK3 Pros:
- Wayland support,
- XInput2 smooth scrolling (can be also implemented in GTK2 by anyone which knows GTK2 and X11),

GTK3 Cons:
- stupid animations, ugly styles (e.g. BlueMenta is ugly on GTK3 and it still has bugs on GTK 3.20),
- broken styles on en every(?) major GTK3 update,
- ugly black window background at startup/resize window,
- ugly background with D&D w/o compositing (black/gray background instead of transparent XShape) since 3.20,
- early 3.20 grabs keyboard on D&D (do they test their library :smiley: ?). Now it is also not good, because it still grabs on non-XI2 events (i.e. firefox still has a problem) - it means: can't use keyboard on D&D,
- probably a lot of bugs compared to GTK2,
- they dropped in GTK3 some useful things,
- who knows what they will destroy in GTK3 in future :smile:

So why Mate wants to use GTK3 only?

---

IMHO it is better to fork and maintain GTK2 instead of force moving to GTK3 which is NOT better than GTK2.

**Comment by raveit65** [comment] 2016-07-26 09:07
Sorry this is an internal disscussion, not for public, please don't post here!

**Comment by monsta** [comment] 2016-07-27 13:52
I probably missed something in discussions... but in https://github.com/mate-desktop/mate-user-share/pull/40 the code is pretty simple. Would it be more complicated in Caja?

**Comment by monsta** [comment] 2016-11-23 16:40
So, we're finally on GTK+3 only now.

**Closed by monsta** 2016-11-23 16:40 UTC
