### ISSUE TITLE
Thumbnail view for image, audio, video, etc. file types

### ISSUE THREAD

**Issue by tranjeeshan** [mate-desktop/caja#415] opened 2015-05-11 04:37 UTC
Caja currently doesn't show tumbnail view of the images, audio and video file types. These are prevalent in Xfce's Thunar from long ago. How about implementing these features in Caja? These thumbnail view helps in previewing the image file especially. 
##

**Comment by jrgp** [comment] 2015-05-25 09:49
Caja is showing me thumbnails just fine. Caja 1.8.2 / packaged with Debian Jessie.

**Comment by monsta** [comment] 2015-06-18 09:18
Same here. Only in icon view though - but I consider this a feature: in other view modes the icons are too small to be used as thumbnails.

**Comment by flexiondotorg** [comment] 2017-01-17 21:19
Duplicate of #153 thumbnails are available in icon view.

**Closed by flexiondotorg** 2017-01-17 21:19 UTC
Labels: unconfirmed

**Comment by desconocidos** [comment] 2017-06-06 08:41
I have upgraded my system from Ubuntu 12.04 to Ubuntu Mate 16.04

Now I can no longer see previews of my graphics files in List View.
Preferences -> Preview is set correctly. **Are you sure this isn't a bug?**

I can see the previews in Icon View but that is no use to me. I need to be able to compare files at a glance, being able to see roughly what the image looks like, filetype, file size and date.
