### ISSUE TITLE
[FR] An option to enable confirmation on moving (deleting) files to trash

### ISSUE THREAD

**Issue by luuuciano** [mate-desktop/caja#632] opened 2016-09-07 23:50 UTC
Yes, we know... moving a file is not deleting it... ok

But you know too, that mate is used by several kind of people, even kids... so, it is not nice having to check trash every day to see if something was deleted by mistake.
In fact, anyone can hit delete key by mistake in caja having focus, and delete whatever it was there without too much notice... and pushing it for a few seconds will delete (move) a bunch of things. Because files are being selected on every moving, if you do not release the key you will be movingtotrash(deleting) all the files and directories on that level and below

If you find that behavior, moving to trash without confirmation, a nice feature ok, that is great. But let the other people to decide if they want to use it or not...
##

**Comment by kn00tcn** [comment] 2016-10-26 09:57
i accidentally deleted when trying to push the 'end' button, a confirmation is needed yes (just a duplicate of the existing one on file systems/devices that cant make a .trash folder)

**Comment by rpoitevin** [comment] 2016-11-18 14:16
Hi!

I up this issue! I teach to blind people how to use a computer and it often happens beginners call me because they lost an icon on the desktop.

Regards.

**Comment by cwendling** [comment] 2017-01-11 10:22
I think Nautilus "solved" this by displaying a notification and allowing to undo the move (both with a button on the notification and with <kbd>Ctrl+Z</kbd>).  Not sure how accessible it is, but it's probably a fairly slick default UI, even if there was an additional confirmation option.
It's generally always best to allow undoing, anyone can accidentally validate a confirmation dialog too.

So I'd up this as an easy solution, and suggest trying to implement undoability in the long term :)

**Comment by lukefromdc** [comment] 2017-01-11 16:32
You can undo moving a file now in Caja with the menubar's edit>undo option. To undo deleting a file(not moved to trash) would be something else altogether, in fact that's a data recovery job for tools like Photorec. Been there, done that.

**Comment by kn00tcn** [comment] 2017-01-12 05:18
-if the device/partition/filesystem lacks a trash, a confirmation is needed
-if you delete from the desktop, you have to open a new caja window to reach the edit>undo menu, some people wont realize this so undo should show up in the desktop right click menu
-confirmation would be nice in general at all times like my example of my finger missing the end button

i dont remember if ctrl+z does anything on the desktop

right now i'm flipping between xfce & mate, disappointed in the glaring issues in both yet certain things are too good to give up, i have no choice but to start developing... this is on top of the need to make a solid gtk+multiple decorators+multiple panels theme

luke, are you implying you have no interest in adding a notification? this sounds like a simple enough thing for me to make as a first attempt, some pointers or tips would certainly be nice though

**Comment by lukefromdc** [comment] 2017-01-12 05:21
I have limited time-especially now with other things going on in this town. Also, I don't really know where to start on that particular job unless Nemo or Nautilus already have a simiar feature.

**Comment by lukefromdc** [comment] 2017-01-12 05:25
https://github.com/cwendling , do you know approximately when Nautilus did something like this, or the file that was changed? I would need one or the other to find the commit as Nautilus gets thousands

**Comment by cwendling** [comment] 2017-01-12 08:44
> You can undo moving a file now in Caja with the menubar's edit>undo option.

Oh, indeed, I missed that.  That's great :)

> To undo deleting a file(not moved to trash) would be something else altogether, in fact that's a data recovery job for tools like Photorec. Been there, done that.

Yeah sure, in the case of permanent deletion it should ask and that's all.  It does on <kbd>Shift+Del</kbd>, that's good.  But apparently it doesn't when trying to move to trash but there's no trash: I tried in a /tmp/ file and it didn't ask, and somewhat confused the undo history that thought it could undo something but couldn't.

**Comment by cwendling** [comment] 2017-01-12 08:45
> @cwendling , do you know approximately when Nautilus did something like this, or the file that was changed?

Not really, sorry.  I think it would be around 3.18 or alike, but I'm not sure at all.  Maybe check the news file for it, or that author's blog?  Sounds like an important enough feature to be listed.

**Comment by kn00tcn** [comment] 2017-01-12 09:06
if the exact dialogue already exists in shift+del, then it would make sense to reuse that code if a new option of 'always confirm deletion' is added to settings

adding it to my list of things to attempt to work on...

**Closed** 2017-02-07 13:51 UTC

**Comment by monsta** [comment] 2017-02-07 13:53
Ok, this feature is now in, #723 is merged.
