### ISSUE TITLE
In-built search function fails to search hidden directories

### ISSUE THREAD

**Issue by JoelleEmmily** [mate-desktop/caja#79] opened 2013-02-17 14:30 UTC
In-built search function fails to search hidden directories

![search](https://f.cloud.github.com/assets/3618013/203962/61680cfa-8156-11e2-8aa5-a4f20f88b743.jpg)
##

**Comment by flexiondotorg** [comment] 2017-01-17 18:55
Test on Ubuntu MATE 17.04 with MATE 1.17. Even showing hidden file in Caja and selecting "Show hidden and backup files" in the MATE Search Tool doesn't change the search results, hidden directories are not searched.

**Comment by lukefromdc** [comment] 2017-01-17 19:12
This is also true of mate-search-tool, so whatever has the problem is code common to both

**Comment by flexiondotorg** [comment] 2017-01-17 20:13
Duplicate of https://github.com/mate-desktop/mate-utils/issues/163

**Closed by flexiondotorg** 2017-01-17 20:13 UTC
Labels: confirmed

**Comment by dmitry-kulikov** [comment] 2018-07-13 18:50
Currently in Ubuntu Mate 18.04 mate-search-tool is able to search hidden files, while search in caja is not.
MATE caja 1.20.2
![screenshot at 2018-07-14 00-43-17](https://user-images.githubusercontent.com/3766212/42708404-0570667c-86ff-11e8-9825-7238fd8a26ff.png)
I tried Show Hidden Files (Ctrl+H) but there are still no results.

mate-search-tool 1.20.0
![screenshot at 2018-07-14 00-22-07](https://user-images.githubusercontent.com/3766212/42708515-57a24bc2-86ff-11e8-8348-9e7cc895b200.png)
