### ISSUE TITLE
GTK+3: impossible to rename file(s) in compact view when scrollbar is shown

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/caja#670] opened 2016-10-30 22:56 UTC
caja in "**compact view**" mode, when there're many files/folders so there's a scroll bar on the bottom I can rename **only** files/folders on first column

debian bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840412

**Comment by sc0w** [comment] 2016-10-30 23:00
I upload this video:

https://mega.nz/#!cFxyiRrb!ZvFOSErIeBrsZkQ1CJlIacllzTdcDyMa2NUhRgclYdI

**Comment by lukefromdc** [comment] 2016-10-30 23:06
I can confirm this with MATE 1.17 and GTK 3.22

**Comment by sc0w** [comment] 2016-10-31 00:04
I can't reproduce it on the **/home/username/** and **/home/username/downloads/** folders

( **/home/scow/** and **/home/scow/Descargas/** on my system )

**Comment by sc0w** [comment] 2016-10-31 01:43
with caja 1.8.2 (debian jessie) it works as expected, I can rename

**Comment by lukefromdc** [comment] 2016-10-31 03:54
OK, this wounds like it might be a GTK3-only issue

**Comment by kn00tcn** [comment] 2016-11-03 01:53
i noticed the columns shifted when file (100) was made, not sure if relevant but the way to rule that out is to have a really small caja window with less than 100 files

**Comment by lukefromdc** [comment] 2016-11-25 19:53
Still present with GTK 3.22.4

**Comment by monsta** [comment] 2016-11-25 20:35
Yes, I see it with 3.22. Weird issue...

**Comment by monsta** [comment] 2016-11-25 20:38
I also see it with 3.20.9 (in Ubuntu 16.10).

**Comment by kn00tcn** [comment] 2016-11-27 00:26
OH, didnt fedora issue an update a few days ago that fixed rename when scrollbar is present? the exact use case was filezilla, if there is no scrollbar, you can rename, but if there is a scrollbar, you VISUALLY dont see a change, but it is in fact renaming

https://bugzilla.redhat.com/show_bug.cgi?id=1381765

i was able to see it in action & see it fixed after update, but i forgot about this caja thread... although i dont think fedora is gtk3 for caja yet is it

**Comment by lukefromdc** [comment] 2016-11-27 00:44
WxWidgets is not used in Caja so the filezilla fix does not apply here, but by running sudo caja so that overlay scrolling(which I normally hate) was enabled I was found that file renaming worked if overlay scrollbars were enabled. This is not an acceptable workaround for those of us who rarely or never use compact view and hate overlay scrollbars but might point to the issue,

Also, in some but not all cases, when closing the "sudo caja" instance after having used the compact view I got these warnings on close:

```
(caja:13673): Gtk-CRITICAL **: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(caja:13673): Gdk-CRITICAL **: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(caja:13673): Gdk-CRITICAL **: gdk_window_show_internal: assertion 'GDK_IS_WINDOW (window)' failed

(caja:13673): Gtk-CRITICAL **: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(caja:13673): Gtk-CRITICAL **: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by kn00tcn** [comment] 2016-11-27 00:58
the message on bugzilla is saying gtk3 with overlay scrolling disabled (supposed disabled by default in mate) results in some kind of rename bug, my implication is that https://github.com/wxWidgets/wxWidgets/commit/8d7e0d045250fa78a7e7d5a25cecee43bb75db3a this change they did might be relevant for us, or anything else that that scott guy found

another idea is maybe gtk bug reports or changes might also know the cause if our potential clue is 'overlay scrolling disabled'

**Comment by monsta** [comment] 2016-12-01 17:47
That stupid overlay scrolling can be enabled if you wish to test it - set ```gtk-overlay-scrolling``` key in ```org.mate.interface``` schema to true and restart the session.
Restart is needed as the actual setting is an environment variable, and it's set by mate-session-manager when it starts the session (https://github.com/mate-desktop/mate-session-manager/commit/725910927048248426f2224762506ef7008f2429).

**Comment by monsta** [comment] 2017-04-15 15:39
@raveit65: I guess https://github.com/mate-desktop/caja/pull/759 also fixes this one? Because I can't reproduce it anymore with current git master and GTK+ 3.22.11.

**Comment by raveit65** [comment] 2017-04-15 15:59
Seems so, i can't reproduce it here with huge folders, but i never tried to reproduce it in that kind of view.
Btw. is it normal that horizontal scrollbar is used in compact-view?
...how weird is that :-)

**Comment by monsta** [comment] 2017-04-15 16:14
Well, in this view files/folders are placed in columns from left to right, and if you reduce window height, there will be more columns placed to the right. So there's only a horizontal scrollbar.

**Comment by monsta** [comment] 2017-04-15 16:36
I also built https://github.com/mate-desktop/caja/pull/761 with GTK+ 3.20.9 (in Ubuntu 16.10), and I can confirm it fixes this issue there as well. Since it was only reproducible with 3.20 and 3.22, I think it's indeed fixed now.

**Closed by monsta** 2017-04-15 16:36 UTC
Labels: confirmed
