### ISSUE TITLE
Startup sort option issue

### ISSUE THREAD

**Issue by motoschifo** [mate-desktop/caja#359] opened 2014-12-08 08:23 UTC
Everytime I start caja the files are sorted by date/time descending.
I changed sort options and clicked the column header but at next start the view is correct, but at next boot is always resetted to date/time sort. The options in the preferences pane are never changed.
How can this be solved?

Not all folders do this, only one that I use often (the "download" folder).
Is this a bug?
Can I select the default sort options with command line switches? That would be a great feature, useful to be used in custom launchers.
##

**Comment by flexiondotorg** [comment] 2017-01-17 20:48
I can't reproduce this on Ubuntu MATE 17.04. Closing, if this is still an issue, please re-open.

**Closed by flexiondotorg** 2017-01-17 20:48 UTC
Labels: unconfirmed
