### ISSUE TITLE
Grid Alignment of Icons on the Desktop

### ISSUE THREAD

**Issue by BT-Justice** [mate-desktop/caja#441] opened 2015-07-18 21:21 UTC
Ubuntu MATE 14.04.2 LTS is now my daily driver OS. I like it a lot. There is only one thing about it that annoys me and that is the alignment of icons on the desktop. If you make them smaller and then enable "Keep Aligned", they are aligned left and right but not up and down. Is there some way to make them behave more like the Windows desktop icons do? Aligned to a grid? Aligned left/right/up/down?

I did report this to the MATE Forum:

http://forums.mate-desktop.org/viewtopic.php?f=17&t=3636

And on the Ubuntu MATE Forum:

https://ubuntu-mate.community/t/grid-alignment-of-icons-on-the-desktop/1794

**Comment by BT-Justice** [comment] 2015-07-18 21:25
Here is my current desktop with Keep Aligned enabled.  As you can see, the icons are not quite aligned correctly:

![screenshot-2](https://cloud.githubusercontent.com/assets/12742232/8763577/65a57f66-2d69-11e5-8efd-6ce7810004cd.png)

And here is the same desktop after I click on "Organize Desktop by Name".  Too much space between rows and still not aligned quite right:

![screenshot-3](https://cloud.githubusercontent.com/assets/12742232/8763578/8fbd6782-2d69-11e5-885e-1d9f92466cb1.png)

**Comment by monsta** [comment] 2015-07-20 15:14
same as https://github.com/mate-desktop/caja/issues/373?

**Comment by BT-Justice** [comment] 2015-07-20 20:49
Yup.

**Comment by infirit** [comment] 2015-07-20 21:08
closed as dupe of #373

**Closed by infirit** 2015-07-20 21:08 UTC
