### ISSUE TITLE
Cannot rename on case sensitive filesystem

### ISSUE THREAD

**Issue by Zurd** [mate-desktop/caja#1346] opened 2020-01-28 20:43 UTC
#### Expected behaviour
Caja should be able to rename a file "a" to "A". Windows doesn't have this problem and it's not a problem in BASH either with "mv a A".

#### Actual behaviour
Error message: The item could not be renamed. The name "A" is already used in this folder. Please use a different name.

#### Steps to reproduce the behaviour
Mount a case sensitive filesystem or just about anything with CIFS and try to rename. I'm actually using a ReadyNAS which is using btrfs but because it is mounted in CIFS, it is case sensitive.

#### MATE general version
1.22.1

#### Package version
?

#### Linux Distribution
Linux Mint

**Comment by lar3ry** [comment] 2024-03-11 18:53
Confirmed for Ubuntu MATE V 22.04
This has been bothering me ever since I started using Ubuntu.

**Comment by lukefromdc** [comment] 2024-03-11 19:20
This cannot be changed within caja in any filesystem that is case-sensitive, as that's not where the problem is. The characteristicsm of filesytems (case sensitive or not included) are set by the filesystem code in the kernel. There is work in the linux kernel itself ongoing to allow case-insensitive EXT4 filesystems, but that's the only place this can be changed: in the kernel. Not sure but I think that may become available in linux 6.9 kernels.

A file manager cannot tell the kernel to do something it does not support and expect it to work. Closing this as nothing can be done here, you might want to open a report against the Linux kernel itself or chime in on any existing reports of same,

**Closed** 2024-03-11 19:20 UTC

**Comment by lar3ry** [comment] 2024-03-11 22:09
Thanks Luke. I had not realized that a filesystem could be case-concious.
I guess I assumed that the OS was the sole arbiter of case-sensitivity.
I sincerely hope that the ongoing kernel work to make EXT(n) filesystems case-insensitive leaves us with a option to tell it which way we want it.

**Comment by Zurd** [comment] 2024-03-11 22:25
I don't know why I said "mv a A" works because I still have the same readynas today, mounted with CIFS and it's not working so forget about this.

Like I said, it is working in Windows, I guess it's mounted with SMB instead of CIFS which might make a difference. I don't know.

It's working fine however in /home with ext4.

Great explanation lukefromdc but you do realize that when renaming a file, Caja could do 2 renaming, like if you wanted from a to A it could do, first, from a to a_tmp123 then from a_tmp123 to A. Thus adding a new feature to Caja.

**Comment by lukefromdc** [comment] 2024-03-11 23:25
I've not worked in Windows in more than a decade, so no surprise I do not know how a remote 
interaction with a Windows system works
