### ISSUE TITLE
Enable hiding directories from recently used document menu

### ISSUE THREAD

**Issue by oz123** [mate-desktop/caja#477] opened 2015-10-25 09:04 UTC
There is a generic solution http://forums.mate-desktop.org/viewtopic.php?f=6&t=2089, which completely disables the menu. 
However, it would be nice to hide directories for discretion or simply because a directory has to many opened files at once. A similar feature exists in Ubuntu's Unity http://askubuntu.com/questions/294901/how-to-disable-recent-files-folder-in-nautilus
##

**Comment by flexiondotorg** [comment] 2017-01-17 21:47
Duplicate of #684.

**Closed by flexiondotorg** 2017-01-17 21:47 UTC
