### ISSUE TITLE
GTK3: unwanted desktop flashes

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#445] opened 2015-08-02 08:32 UTC
Those flashes can be triggered by:
- using caja-dropbox in autostart, you see a flash 2-3 sec after session start
- switching the theme with m-a-p
- if a package-manager update the root file system
- if you browse files on a external drive

With the last 2 cases you don't see the flashes every time.
Running fsck helps to reduce the flashes.
A little video:
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/mate-flashes.ogv
see also http://forums.mate-desktop.org/viewtopic.php?f=16&t=3533&p=11500#p11278

**Comment by lukefromdc** [comment] 2015-09-01 04:04
I've had tbis same issue, caused apparently when disk access is slowed down. Building packages involves enough disk activity to cause the desktop to flash, and once it has flashed once it will easily flash again. This occurs only with GTK 3.16 or above on my boxes. Also, after a flash the editable label for renaming a file loses it's background color. replacing eel-editable-label.c with a hacked version of  Nemo's eel-editable-label.c (just enough changes to let it build) will stop the loss of editable lable background but not stop the flashes themselves. My guess is redrawing is being held up when disk access is slow, and newer GTK versions (the ones with all the compositing issues) are defaulting to white during this redraw, revealing a previously hidden problem.

**Comment by lukefromdc** [comment] 2015-09-28 22:57
The color of these flashes can be controlled to some extent but they cannot be made to disappear by setting them to transparent. I used this code to make them the gray theme background color I use:

CajaWindow, CajaDesktopWindow , FMDesktopIconView .view  {
	background-color: @theme_bg_color;
}

This does not change the color of the normal folder backgrounds (white) nor the desktop, it seems to only control the flash color, at least in my theme.

**Comment by lukefromdc** [comment] 2015-09-28 22:58
Forgot to include this: setting the flashes transparent simply turns them black

**Comment by lukefromdc** [comment] 2015-10-20 02:01
Commits added to Caja on 10-19-2015 seem to have stopped the background of the rename box for a file on the desktop from turning transparent, though they did not stop the flashes. The commits in question replaced deprecated Gtk3 stuff, maybe more of this will stop the flashes?

**Comment by raveit65** [comment] 2015-10-20 13:52
Good to hear that fixing deprecations also fix a bug.
But i couldn't fix all gtk_misc_set_alignment and gtk_{v,h}box on all files, without breaking the desktop view, you should see that in build log.
Need to find out what is wrong here, to apply those fixes.

**Comment by lukefromdc** [comment] 2015-10-20 17:23
Try looking at how current Nautilus or Nemo approach the functions that could
not be changed. I haven't heard of either having the flash problem, but then 
again I have not aggressively tested either as running the desktop with gtk3.16 or
later. If GNOME let Nautilus out the door with that issue I would probably have
seen it on Phoronix as people love to troll on both GNOME and KDE there.

**Comment by raveit65** [comment] 2015-10-20 20:27
Well, i didn't noticed the flashes with running cinnamon or gnome3 on my boxes too.
But handling the background is one thing which is complete different from nemo or nautilus.
In Mate there are 3 packages responable for handling the background, caja, m-s-d and m-s-m.
During gnome3 development all background code was moved to gnome-settings-daemon.
So, it's a bit hard to compare the code.
I think the flashes are caused by a new deprecation with gtk+-3.16,.........maybe.
Or new gtk3 code with 3.16 and caja needs to adjust for this.
Because with gtk+-3.14 we don't have those flashes.

**Comment by lukefromdc** [comment] 2015-10-20 21:08
Yes, this is Gtk3.16 and later problem only, the first times I ever saw
it was with the development versions of GTK3.15 last Spring. In some
themes, simply clicking the window border of a window that is not the
current one could trigger a flash last summer. With the themes that 
attempt to address this it takes much more aggressive behavior to 
trigger it, I see it mostly when installing a Debian package or a 
series of them. 

Nemo also has background handling issues. Nemo's desktop is designed
to be transparent over an underlying background and only works in 
Mutter, GNOME 3, Cinnamon, Muffin, Mutter, Metacity- and in Marco. 
The icons are composited with the image below, black desktop if 
compositing is turned off! Also, Compiz's compositor is incompatable
Compiz gets all kinds of failure to redraw issues unless a special patched 
version of Nemo is used from an Ubuntu PPA.

Nautilus 3.18.1 on my system (Debian Unstable) crashes on load if 
desktop icons are enabled, Nautilus 3.16 with GTK3.17 had issues with
drawing the wrong background at least in my theme.

GNOME seems to consider icons on the desktop as de facto deprecated
and has been trying to kill them since GNOME 3.0. Their user base has
forced them to keep the option to have desktop icons. It may be that they 
moved the code because their original intent was to only draw the background,
which would be a job for gnome-settings-daemon only. Thus changes in 
GTK that create issues may be poorly tested.

**Comment by lukefromdc** [comment] 2015-11-26 05:30
I have written a rough fix which makes the flashes truly transparent but causes high CPU use for the duration of each now-hidden flash if running compiz.  Marco with gtk3.19 seems stop the flashes entirely with existing Caja though this did NOT get an aggressive test. This fix does stop the flashes in every Marco or Compiz setup , with or without compositing in Marco that I have tested so far. Scheduling a hard gtk3.18/Marco test now. Here's the branch with this rough fix plus a named widget for caja windows for gtk3.19:

https://github.com/lukefromdc/caja/tree/flashfix

Like I said, this is rough. It's a request for more eyes on this, not a PR at this point.

**Comment by lukefromdc** [comment] 2015-11-30 06:16
just found out by accident that the Raleigh theme does not flash the desktop when clicking between the desktop and other windows. I then found that the reason I was having such severe issues with gtk3.19 was that I had accidently borrowed the code from Adwaita that makes Caja constantly flash the desktop with that theme:


textview text,
.view {
  color: black;
  background-color: #ffffff; }
  textview text:backdrop,
  .view:backdrop {
    color: #333333;
    background-color: white; }[/code]

The relevant code from this is the .view class, which matches the Caja desktop icon view.  Although some other code in my theme must have overrode this so I never saw that color, it still forced the desktop to reload and triggered the flash.  Removing all references to view:backdrop stops the flashes on clicking between windows and the desktop, but has no effect on flashes caused by heavy disk loads causing slow updates.  Some way to hardcode view.backdrop to always follow the main .view colors in caja or to be ignored by Caja entirely would stop the worst of the flashes in all themes at the price of reduced theming flexablity. I don't know any way of doing this though, or I would have already put it into a css provider with priority application.

**Comment by lukefromdc** [comment] 2015-12-01 18:51
I used what I found about view:backdrop triggering the flashes to write a new "flashfix4" branch where flashes are rare, and if both commits are used the remaining flashes are made transparent. Submitted this PR: 

https://github.com/mate-desktop/caja/pull/485

**Comment by lukefromdc** [comment] 2015-12-14 22:46
Had to close PR #485 as changes in git master gtk3.19.4 broke it. We need a fix that works in any version of gtk3 Caja might be build with. Also found that the flash (in any version of caja-gtk3) comes with a memory leak, about 10MB per flash on my system with over 8GB in some large development directories kept on the desktop

**Comment by raveit65** [comment] 2015-12-14 23:32
@monsta 
Can you please take a look in it?
I don't know how to fix a memory leak issue in caja : -/
In oposite to my previous comments the issue exists also with Mate in gtk+-3.14,.........now.

**Comment by raveit65** [comment] 2015-12-14 23:35
@stefano-k please help

**Comment by lukefromdc** [comment] 2015-12-15 02:41
New PR posted https://github.com/mate-desktop/caja/pull/486 replaced the previous version, now works with gtk3.19 both before and after the commit that broke the previous version.  Had to re-do the repo from scratch after a Github issue though, so if anyone needs the previous version I will make a branch without the latest change (by deleting one line), a "flashfix4-resurrected" branch.

**Comment by monsta** [comment] 2015-12-16 13:21
Memleaks are no good... but first I need to reproduce the flashes in my VM...

**Comment by monsta** [comment] 2015-12-16 13:31
Ok, reproducible even in a VM when changing themes in m-a-p. But I don't see any memleaks...
GTK+3 is 3.18.5 there.

**Comment by lukefromdc** [comment] 2015-12-16 19:44
You might need to have a lot of files or folders with lots of files in them on the
desktop to  notice the memory leak. I've got most of MATE as both source and
the files to tar up into .debs sitting in a folder on my desktop, plus compiz, 
Kdenlive, and GTK itself in others.

I noticed the memory leak while keeping mate-system-monitor open and 
intentionally triggering flashes. This was on gtk3.19, I was looking to see 
how much more ram using an RGBA instead of RGB desktop window was
using. This was a little less than 10MB with a busy jpeg as the background,
47 items on the desktop,and nothing else open in caja and there was no
difference if at least one folder was also open.

I then noticed caja's ram usage went up 10MB or so with every flash and stayed there. 
Worst of all, replacing my flashfree branch with caja from mate-desktop/master did 
not stop the RAM usage from climbing  with every flash, nor reduce the amount of it.

If this is not reproduceable with tk3.18 or earlier might it be a GTK issue and not
a caja issue at all?

**Comment by monsta** [comment] 2015-12-17 13:59
Well, as I see in the comments above, it started with 3.16, so not only 3.18 is affected.

**Comment by raveit65** [comment] 2015-12-17 14:06
It's a bit weird,
first i say the flashes only with 3.16 and not with 3.14.
But now i can reproduce them in f21 or Rhel/Cento-7.2 with gtk-3.14 too.

**Comment by raveit65** [comment] 2015-12-17 14:13
Means we have maybe a regression, because i started build mate gtk3 with 1.9.x releases in f21.

**Comment by monsta** [comment] 2015-12-17 14:32
It's getting complicated... :smile:

**Comment by lukefromdc** [comment] 2015-12-18 06:00
I just found that SpaceFM used to have a problem like this, but with a different cause:

http://ignorantguru.github.io/spacefm/news.html (well down from the top, about 1/2 inch on my Firefox scrollbar)

I tested Caja to see if this was the culprit here by turning off thumbnailing, caja still flashed the same in Adwaita with my last mate-desktop/master build so this was not a factor. Still, something else could be updating continuously or just plain having a single stalled update(as I suspect) thus causing this.

**Comment by lukefromdc** [comment] 2016-01-10 20:11
I just made a new branch:  https://github.com/lukefromdc/caja/tree/flashfix+dev-gtkstylecontext , only to find that the dev-gtkstylecontext branch works with the flashfix patches ONLY with gtk3.19. This is because the style changes to that branch cause the transparent style to be applied to selected icons, turning them black and turning the rubberband box invisible. In GTk3.19.6, it is possible to use a negation selector to exclude the :selected and the :active states from this, but that does not work in gtk3.18. I was looking for error messages from hardocding the new gtk3.19 caret color styles, which cause flashes again in Adwaita. Got no such messages and the caret-color coding was silently ignored in gtk3.18-but no matter what I did I either got transparent flashes on clicking between desktop and a window (that quickly use up all the X clients), or else the selected icons turned black. I will keep looking for a fix for that for gtk3.18, assuming the dev-gtkstylecontext branch might be merged to master.

**Comment by raveit65** [comment] 2016-01-10 21:42
dev-gtkstylecontext needs some changes in theme.
To avoid that a selected file goes black if the window lost focus use something like this
```
.view:active,
.view:selected {
    background-color: shade(@theme_selected_bg_color, 1.10);
    background-image: -gtk-gradient (linear,
                                     left top, left bottom,
                                     from (shade(@theme_selected_bg_color, 1.0)),
                                     to (shade(@theme_selected_bg_color, 1.1))); 
    color: @theme_selected_fg_color;
    text-shadow: 0px 1px @theme_selected_shadow_color;
    text-shadow: none;
}
```
.view:active, must be added to .view:selected .
Than EelEditableLabel has a new style class .entry
ie.
```
EelEditableLabel.entry,
EelEditableLabel.entry:focused {
   border-image: none;
   border-width: 1px;
   border-color: @theme_fg_color;
   box-shadow: none;
   border-radius: 3px
}
```
Unfortunatly i couldn't fix the flashes :-/
The problem must be in eel-backgrounds itself, this is the only file which i didnt touched.
In next round of backporting nautilus commits i will try out this one.
https://git.gnome.org/browse/nautilus/commit/?id=ef74d171892ed7189b4a52695ae8de575d2dac1a
Here eel-background usage is replaced with a internal function.

Btw, i didn't test your flash fixes with that branch

**Comment by lukefromdc** [comment] 2016-01-10 21:46
What I got was this: I had to exclude view:active and view:selected from being
overridden by the transparent view set in the flash fixes. Doing that made for
the transparent flashes in gtk3.18, which did not stand up to any changes in
state bringing a theming change. In gtk3.19, no flashes resulted from this
exclusion. Oh well, the combined branch should be considered gtk3.19 only,
good enough for my use. Do not use it for packages that might be run with
older GTK versions unless I find another workaround.

Also, I will try that nautilus commit myself.

**Comment by raveit65** [comment] 2016-01-10 21:48
Btw. this branch fixes https://github.com/mate-desktop/caja/issues/81
And that changing a theme change also the selected color

**Comment by raveit65** [comment] 2016-01-10 21:51
i forgot to say the mentioned nautilus commit has a lot of followed commits

**Comment by lukefromdc** [comment] 2016-01-10 22:02
Also be aware that the most recent versions of Nautilus have been 
notorious for background issues like getting an opaque unchangeable
background or in some cases no opening at all with icons on the desktop
set. GNOME doesn't really care about that, they have been trying to kill
icons on the desktop since the initial release of GNOME 3.

**Comment by lukefromdc** [comment] 2016-01-11 01:09
I just managed to build Caja with that commit hand-edited into place and a bit
of improvisation. Broke the setting of light/dark text on the desktop, selected
items defaulted to white-and Caja still flashed white.

**Comment by lukefromdc** [comment] 2016-01-11 01:50
The widget carrying the white flash seems to be the FMIconContainer, as the flash
is the color of whatever background is assigned to it by the .view class it carries.
When the desktop is showing normally this is transparent but on a slow reload the
normal .view theme is getting applied to it. 

The FMDesktopIconVIew color does not seem to affect this, so that entry for 
transparency can be removed. Looks like a slow reload of the icon container causes
the flash.

**Comment by raveit65** [comment] 2016-01-11 02:12
Here is is a attempt which works on top of dev-gtkstylecontext branch,
similar to your fix.
https://gist.github.com/raveit65/eb58a5f7668c05696c75
Taken from https://git.gnome.org/browse/nautilus/commit/?id=f0f36c876e4810b190a82e3a953d9263c106447f
Unfortunatly it breaks background-fade too.
Tested with gtk+-3.16 , (Alpha)........ use it with care.

**Comment by lukefromdc** [comment] 2016-01-11 02:44
https://gist.github.com/raveit65/eb58a5f7668c05696c75 did not work with gtk3.18 or 3.19 in my tests. Patched the files built it-and got flashes on both gtk versions. Also dark text on the desktop again.

**Comment by raveit65** [comment] 2016-01-11 03:27
Opps, my fault.
Apply those patches on top of the branch
https://gist.github.com/raveit65/ee913c63bb6a284999b7
https://gist.github.com/raveit65/0c16103aee7466821877
Than add something like this to your theme:
```
EelEditableLabel.entry,
EelEditableLabel.entry:focused {
   border-image: none;
   border-width: 1px;
   border-color: @theme_fg_color;
   box-shadow: none;
   border-radius: 3px
}

.caja-canvas-item {
    border-radius: 4px;
}

/* desktop mode */
CajaDesktopWindow.background .caja-canvas-item {
    color: white;
    text-shadow: 1px 1px alpha (#000000, 0.8);
}

CajaDesktopWindow.background .caja-canvas-item:active {
    background-image: none;
    color: @theme_text_color;
}

CajaDesktopWindow.background .caja-canvas-item:selected {
    color: @theme_selected_fg_color;
}

CajaDesktopWindow.background .caja-canvas-item:active,
CajaDesktopWindow.background .caja-canvas-item:prelight,
CajaDesktopWindow.background .caja-canvas-item:selected {
    text-shadow: none;
}
```
With .caja-canvas-item you are able to set the font color now.
Local i use this 2 patches too, didn't expected that they are needed for dev-gtkstylecontext branch.
I wanted apply theme after gtkstylecontext stuff is in master, sorry for this.
This works here with gtk+-3.18 and 3.16.

**Comment by raveit65** [comment] 2016-01-11 03:30
To be more precise, i do not see any flash if switching the gtk theme.

**Comment by lukefromdc** [comment] 2016-01-11 04:15
The theming works in both gtk3.18 and 3.19, but the desktop still flashes. In gtk3.18
it is especially bad, flashing every time you click on the desktop. In gtk3.19 it will
flash when installing a bunch of debian packages. Doesn't flash on changing themes
but that's it.

**Comment by lukefromdc** [comment] 2016-01-11 06:12
OK, combining this latest patch set with my own flash patches finally made
a Caja build that does not flash when clicking on the desktop in gtk3.18 in
most themes or on gtk3.19.6 in any theme.  Started with the dev-GtkStyleContext
branch, applied your patches and then my flashfix patches:

https://github.com/lukefromdc/caja/tree/gtkstylecontext+GtkRender+flashfix-2

Here are my test results:

GTK3.18 results:
Adwaita and Blue Submarine still problematic, most other themes (Raleigh, BlackMATE, BlueMenta, and my own all tested) work. 
Transparent "flash" on theme change-and in Adwaita or Blue Submarine on clicking on the desktop. This also observed w/o any of
these patches though with the dev-GtkStyleContest branch

Gtk3.19.6 results:
All tested themes stable, invoking transparent "flash" requires installing debian packages or similar heavy loads. No flashes on theme changing from dconf-editor. 

Have theming issue with clear rubberband on the desktop, will deal with that next. Selected items look fine.

**Comment by lukefromdc** [comment] 2016-01-11 07:39
This commit fixes the rubberband issue:

https://github.com/lukefromdc/caja/commit/9df5a961d83b9493cbe9d4cbba3c201b467b7afe

OK, this branch now combines the dev-GtkStyleProperty branch with your patches, my
fixes for the desktop flash, and (in gtk3 only) code cribbed from Nemo in
caja-icon-container.c Two complete versions of the "start_rubberbanding" function, the 
Nemo one builds in GTK3, the Caja one with all GTK3 splitouts removed in GTK2.

This works: I've got the stable results of the last tests and finally get both selected items
and the rubberband following the theme without making GTK 3.18 flash on clicking the
desktop.

**Comment by raveit65** [comment] 2016-01-11 18:43
You're right, my flashfix only works for gtk theme changes, i noticed a flash when caja-dropbox pulls in during session start.
I added the GtkRender patches to dev-GtkStyleProperty branch and some more backports from nautilus for caja-icon-canvas.
I applied also your rubberband commit because it is the same like https://git.gnome.org/browse/nautilus/commit/?id=ca7f81e2e9adf325effa11fc55aace4a087ab61b
Thank you.
Btw. what does rubberband mean in caja styling? Which element is it?
Ok, i will try to backport 2 or 3 patches from nautilus for caja-icon-container.c than this branch is closed.
Btw.
some more styling changes are needed, ie. Blue-Sumarine
```
CajaNavigationWindow.background .view.caja-canvas-item {
    color: @theme_fg_color;
}

CajaNavigationWindow.background .view.caja-canvas-item:active {
    color: @theme_fg_color;
}

CajaNavigationWindow.background .view.caja-canvas-item:selected {
    color: @theme_selected_fg_color;
}
```
and EelEditableLabel.entry needs a text-shadow: none.

**Comment by raveit65** [comment] 2016-01-11 19:45
Looks like that the flashes are gone with 'GTK3 icon-container: don't chain up style-updated for the desktop container ' :smile: 
No flashes if switching gtk theme or with dropbox start.

**Comment by raveit65** [comment] 2016-01-11 19:46
tested with gtk+-3.16/18

**Comment by lukefromdc** [comment] 2016-01-11 23:30
The rubber band is the box drawn around icons being selected. With the new
commit it responds to the rubberband and .rubberband selectors.

**Comment by lukefromdc** [comment] 2016-01-11 23:57
I just tested this by dropping the file into my build directory and reverting my own
flash fixes there. Worked fine in gtk3.19 and I was not able to force a flash by
installing a bunch of Debian packages while copying a file to a flash drive.  Further
testing will tell for sure but we may not have the solution to this.

**Closed** 2016-01-13 14:15 UTC
Labels: confirmed

**Comment by lukefromdc** [comment] 2016-01-13 22:59
Built and installed from newly merged master, works well
