### ISSUE TITLE
Gtk+-2 - 1.16.0 Visual Regressions 

### ISSUE THREAD

**Issue by MDykstra** [mate-desktop/caja#651] opened 2016-10-07 14:27 UTC
Since Mate 1.160.0 update on Arch Linux:

Text below icons remains black when setting `Edit - Backgrounds and Emblems` to a dark background color for the main iconview of Caja. The icon text-color previously would change to white.
![black-text](https://cloud.githubusercontent.com/assets/1680211/19193203/7ecc5fe6-8ca9-11e6-8ec4-eaaa4f43695d.png)

Selecting icons and dragging to the right and back to the left leaves ghost selection areas. 
Dragging fully to the right it is possible to loose icons, which should remain in view. 
This same issue has happened in the past.
![drag-outside](https://cloud.githubusercontent.com/assets/1680211/19193198/7a00f580-8ca9-11e6-8068-017a6a747074.png)

**Comment by lukefromdc** [comment] 2016-10-07 17:30
Is this with GTK 3.22? A lot of changes to how the desktop is rendered were
necessary to get the desktop to work at all with some radical changes made
in GTK during the 3.21 development cycle.

**Comment by MDykstra** [comment] 2016-10-07 23:17
It is still the GTK2 version. I should probably start to move everything to GTK3 and report on that.

**Comment by MDykstra** [comment] 2016-10-10 10:39
On Caja-GTK3 I cannot drag-and-drop a color from `Edit - Backgrounds and Emblems` onto the main viewing pane. Additionally, the color patches initially don't show up in the dialog; only after resizing `Backgrounds and Emblems` dialog window do they appear.

**Comment by monsta** [comment] 2016-10-10 15:01
> Text below icons remains black when setting Edit - Backgrounds and Emblems to a dark background color for the main iconview of Caja. 

Confirmed, except for when color is completely black (the last one in the list).
No idea why, I thought we already fixed that stupid issue once.

> Selecting icons and dragging to the right and back to the left leaves ghost selection areas. 

Can't reproduce this one...

> On Caja-GTK3 I cannot drag-and-drop a color from Edit - Backgrounds and Emblems onto the main viewing pane. Additionally, the color patches initially don't show up in the dialog; only after resizing Backgrounds and Emblems dialog window do they appear. 

Yes, we know - #506 :disappointed:

**Comment by zaps166** [comment] 2016-10-10 19:32
> Selecting icons and dragging to the right and back to the left leaves ghost selection areas. 

I've got the same bug using GTK2 since 1.16.0. On GTK3 Caja doesn't have this bug.

**Comment by zaps166** [comment] 2016-10-13 09:49
> Selecting icons and dragging to the right and back to the left leaves ghost selection areas. 

Caused by: https://github.com/mate-desktop/caja/commit/1f7ab5dcbca155f331735a8483d768ea0c349c18 and then https://github.com/mate-desktop/caja/commit/f02d495258535739320e340f809f1e8392aca7af

**Comment by monsta** [comment] 2016-10-16 19:06
> Selecting icons and dragging to the right and back to the left leaves ghost selection areas. 

Ok, I was able to reproduce https://github.com/mate-desktop/caja/issues/659 - is it the same? It looks so to me. That issue is fixed now in https://github.com/mate-desktop/caja/pull/662.

**Comment by zaps166** [comment] 2016-10-16 20:47
> Selecting icons and dragging to the right and back to the left leaves ghost selection areas.
>> Ok, I was able to reproduce #659 - is it the same? It looks so to me. That issue is fixed now in #662.

Yes, this is the same, we've written about the same commits which causes a regression in two different bug reports :)

**Comment by raveit65** [comment] 2016-10-17 04:22
Commits are cherry-picked to 1.16.
https://github.com/mate-desktop/caja/commit/a7ef765a1c9f1d7796a4e168ae2398af2368d3ad
https://github.com/mate-desktop/caja/commit/fb4d4960d6e4efa3fd85751ae373abafa20967df
So, do they fixes the issue?

**Comment by zaps166** [comment] 2016-10-17 10:14
@raveit65 Yes, thanks!

**Closed** 2016-10-17 11:14 UTC
