### ISSUE TITLE
Krita and all wine applications shows multiple times in "open with" dialog

### ISSUE THREAD

**Issue by unxed** [mate-desktop/caja#697] opened 2016-12-31 01:31 UTC
![_071](https://cloud.githubusercontent.com/assets/1151423/21575071/e3ef6120-cf11-11e6-999c-2025a7d290de.png)
![_072](https://cloud.githubusercontent.com/assets/1151423/21575073/e8f6192a-cf11-11e6-9838-b511f2e27b6a.png)
![_073](https://cloud.githubusercontent.com/assets/1151423/21575075/ed835930-cf11-11e6-9833-bae72676c30e.png)

**Comment by unxed** [comment] 2016-12-31 01:32
In right-click (on file) context menu those apps are also shown twice.

**Comment by lukefromdc** [comment] 2016-12-31 06:08
This also appears with Pluma shown twice in the index.theme right click menu in Caja (newest GIT master), Nemo, and three times in the harder to get to "select application" menu for Nautilus.  A fix for one might be a fix for all in the best case, worst case is its in the applications themselves.

**Comment by kn00tcn** [comment] 2017-01-12 05:54
hey what gtk & window theme are you using? or is it the default one that mint chose?

i dont think i've seen this happen on fedora, but i dont use wine apps

i'm curious how this list is stored or generated, also how wine creates the existence of apps in the linux OS's format (for menus, etc)

**Comment by unxed** [comment] 2017-01-13 05:56
> or is it the default one that mint chose?

yep

**Comment by flexiondotorg** [comment] 2017-01-17 14:48
Interesting:

    ls -1 /usr/share/applications/krita*.desktop | wc -l
    16

Krita has 16 `.desktop` files. I think `mate-menus` is probably doing the "right thing" here.

**Comment by unxed** [comment] 2017-01-19 05:45
```
ls -1 /usr/share/applications/kde4/krita*.desktop | wc -l
16

ls -1 ~/.local/share/applications/wine-extension-*.desktop | wc -l
48
```

**Comment by flexiondotorg** [comment] 2017-01-19 07:59
Are we agreed this is not a bug? If so, please close this 🙂

**Closed** 2017-01-19 19:07 UTC

**Comment by unxed** [comment] 2017-03-26 00:39
https://github.com/mate-desktop/mate-menus/issues/46

**Comment by DrReD** [comment] 2017-03-26 03:35
Isn't it just a matter of supporting "NoDisplay" as per the specs?
In which case, couldn't it be considered a feature request?
