### ISSUE TITLE
Gtk3 tracking report

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#482] opened 2015-11-11 12:36 UTC
This report list only Gtk3 bugs which needs to be fixed before caja can use for production with gtk3.
Please open a single report first if you found a new issue, mention there that you think this is a blocker report, and we will add them here.

MUST:
- GTK 3.21.3: no desktop redraws or bg changes until restart
  https://github.com/mate-desktop/caja/issues/575 fixed with
  https://github.com/mate-desktop/caja/commit/6f3c1e4dd60264244be353b42293cd0995589e5e
  https://github.com/mate-desktop/caja/commit/3fd59d25d213f53761691aa81095623fe5895e52
  https://github.com/mate-desktop/caja/commit/b8f0f58e84776d828964dc0ecfd5604421222268
  https://github.com/mate-desktop/caja/commit/c8ea6aafe576d204b4423c868754b4580c52d397
  https://github.com/mate-desktop/caja/commit/3d61fc43087764d2a99c8cdce4bebc697ba961bc
  https://github.com/mate-desktop/caja/commit/190d8b70717fc2b91507ae7695acdeee894c11cd
  https://github.com/mate-desktop/caja/commit/8d658fa4f3790972c38e04df23eaa7b88b5066d8
  https://github.com/mate-desktop/caja/commit/8c926115c99100a581abfd20dced5dfbe4922792
  https://github.com/mate-desktop/caja/commit/f5164f75918a8e65ccde9565c4fd9f366064172e
- GTK3: unwanted desktop flashes
  https://github.com/mate-desktop/caja/issues/445 fixed with https://github.com/mate-desktop/caja/commit/2c8e8a06a050d43d730475bf05cbd07508f32160

SHOULD:
- GTK3: Backgrounds and Emblems dialog does not work
  https://github.com/mate-desktop/caja/issues/506

NICE TO HAVE:
- Gtk+-3.21 desktop background-fade regression
  https://github.com/mate-desktop/caja/issues/612 fixed with
  https://github.com/mate-desktop/caja/commit/6f3c1e4dd60264244be353b42293cd0995589e5e
  https://github.com/mate-desktop/caja/commit/3fd59d25d213f53761691aa81095623fe5895e52
  https://github.com/mate-desktop/caja/commit/b8f0f58e84776d828964dc0ecfd5604421222268
  https://github.com/mate-desktop/caja/commit/c8ea6aafe576d204b4423c868754b4580c52d397
  https://github.com/mate-desktop/caja/commit/3d61fc43087764d2a99c8cdce4bebc697ba961bc
  https://github.com/mate-desktop/caja/commit/190d8b70717fc2b91507ae7695acdeee894c11cd
  https://github.com/mate-desktop/caja/commit/8d658fa4f3790972c38e04df23eaa7b88b5066d8
  https://github.com/mate-desktop/caja/commit/8c926115c99100a581abfd20dced5dfbe4922792
  https://github.com/mate-desktop/caja/commit/f5164f75918a8e65ccde9565c4fd9f366064172e
##

**Comment by lukefromdc** [comment] 2016-06-28 02:49
Should be added to this as a MUST:

GTK 3.21.3: no desktop redraws or bg changes until restart
https://github.com/mate-desktop/caja/issues/575

GTK3.21 has now had this problem since June 9,almost 20 days ago and no fix on that end. Assuming that gets to final release GTK 3.22 no distro will be able to use Caja and Gtk 3.22 together unless Caja is not used to manage the desktop.

**Comment by flexiondotorg** [comment] 2017-07-19 07:39
@raveit65 @lukefromdc Can this be closed? 

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by raveit65** [comment] 2017-07-19 07:52
@flexiondotorg 
We have a open **should**  :-)
https://github.com/mate-desktop/caja/issues/506
Btw. there is a last remaining issue with this report.

**Comment by lukefromdc** [comment] 2017-07-19 18:30
That last issue is a failure to draw contents of the backgrounds and emblems dialog except sometimes on first open. Workaround is to resize the window but that is not obvious at all. Looks like a forced-redraw is needed somewhere

**Comment by lukefromdc** [comment] 2018-01-07 19:46
I just found out that GNOME considers a port of nautilus-desktop to GTK4 to be entirely impossible. Instead of fixing GTK4 or Nautilus, they have decided to REMOVE support for icons on the desktop entirely! For GNOME 3.28 desktop icon users are advised by GNOME to install Nemo.
https://gitlab.gnome.org/GNOME/nautilus/issues/158

Thus, any port of Caja (and thus of MATE as a whole) to GTK4 may be impossible short of removing the desktop from Caja and rewriting a new desktop application totally from scratch aimed at GTK4 and presumably wayland. Apparently GTK4 takes out code needed for the canvas to work..

**Comment by alexarnaud** [comment] 2018-01-09 09:29
Le 07/01/2018 à 20:46, lukefromdc a écrit :
> I just found out that GNOME considers a port of nautilus-desktop to GTK4 
> to be entirely impossible. Instead of fixing GTK4 or Nautilus, they have 
> decided to REMOVE support for icons on the desktop entirely! For GNOME 
> 3.28 desktop icon users are advised by GNOME to install Nemo.
> https://gitlab.gnome.org/GNOME/nautilus/issues/158
> 
> Thus, any port of Caja (and thus of MATE as a whole) to GTK4 may be 
> impossible short of removing the desktop from Caja and rewriting a new 
> desktop application totally from scratch aimed at GTK4 and presumably 
> wayland. Apparently GTK4 takes out code needed for the canvas to work..

Is there any bug report on GTK about this issue? It sounds like it is a 
regression if desktop support is no longer allowed.

If I understand well, desktop support depends on canvas?

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by lukefromdc** [comment] 2018-01-09 18:30
GNOME would probably close such a bug as "wontfix" advising the necessary canvas support be re-implemented in the application. If the exact removed code was found, it could be also re-implemented as "libdesktop4" or "libgtk-4-0-extras" or some such thing. GNOME is no longer including the code in GTK, but it still exists in GTK3 and thus still exists as source.

Finding it, of course, is our problem and the Cinnamon team's problem. I hope that by the time GTK3 gets old and poorly supported, there is another LTS version of GTK

**Comment by lukefromdc** [comment] 2018-02-11 23:04
I finally found a way to mostly fix the remaining elements of  https://github.com/mate-desktop/caja/issues/506 ,though it takes a few seconds for the function in which this is fixed to get called.
https://github.com/mate-desktop/caja/pull/917

**Comment by shirishag75** [comment] 2018-02-13 19:33
@lukefromdc , the only thing remaining I guess is to close this tracking report now that everything is fixed, and put a release out so people can test it on part of gtk 3.22.

**Comment by lukefromdc** [comment] 2018-02-13 19:48
I would guess this would be in caja 1.20.1, 1.20.0 just came out.

**Closed** 2018-02-13 19:49 UTC

**Comment by raveit65** [comment] 2018-02-13 20:04
Great gtk+-3 milestone is at 100%  \o/

**Comment by flexiondotorg** [comment] 2018-02-13 20:53
Congratulations! Thanks @lukefromdc for closing out the final issue. Well done 😀

**Comment by shirishag75** [comment] 2018-02-13 21:20
yup, great to see gtk+3 finally behind us, now let's see if there is something left for 3.20.1 release to come out.
