### ISSUE TITLE
Add ability to span a screen quarter by a window when you drag it to one of the screen corners

### ISSUE THREAD

**Issue by sh2ka** [mate-desktop/caja#378] opened 2015-01-26 11:27 UTC
Now it allows to span to maximized when you drag window to top of the screen, to left and right screen middles when you drag window to the left and to the right of the screen accordingly.
KDE has great feature - to span window to one of the screen quarters.
I think it's nice because many peaple has big wide monitors and they allow not just to split screen into 2 parts, but into 4 parts as well.

**Comment by stefano-k** [comment] 2015-01-26 12:33
Duplicate of https://github.com/mate-desktop/marco/issues/101

**Closed by stefano-k** 2015-01-26 12:33 UTC
