### ISSUE TITLE
xattr integration feature request

### ISSUE THREAD

**Issue by xsleonard** [mate-desktop/caja#317] opened 2014-08-30 05:34 UTC
I plan to work on this but am seeking feedback.

In my case, I realized chromium sets the `user.xdg.origin.url` xattr to the url from where a file was downloaded.  I'd like to be able to view this information in the Properties panel for a file.

To use xattrs, your filesystem must support it and it may need to be enabled with the `user_xattrs` option in `/etc/fstab`.  The `attr` package in mint/ubuntu repos provide `setfattr` and `getfattr` commands for writing and reading the values.

Specifications for common xattr key names:
http://www.freedesktop.org/wiki/CommonExtendedAttributes/
##

**Comment by DavidParkin** [comment] 2015-06-24 08:35
I already have an extension that display xattrs. I wrote it before I found the notes tab mentioned in my other issue. It is not too difficult to display the info, update is different.

**Comment by flexiondotorg** [comment] 2017-01-18 00:32
Duplicate of https://github.com/mate-desktop/caja-extensions/issues/24

**Closed by flexiondotorg** 2017-01-18 00:32 UTC
Labels: feature request
