### ISSUE TITLE
Crash when moving my cursor over a file in my trash

### ISSUE THREAD

**Issue by AXDOOMER** [mate-desktop/caja#621] opened 2016-08-25 02:59 UTC
Hello,

I got a crash whenever I was moving my cursor over a file in my trash. (trash:///)

I later went in my trash using 'root' and I got the following error messages printed in my terminal: (read the next comment)

I couldn't see the file while using 'root' (may be I just missed it?), so I used the terminal to go in "/home/axdoomer/.local/share/Trash/info" and "/home/axdoomer/.local/share/Trash/files" and deleted the file manually using 'rm'.

I have MATE 1.8.1 and Caja 1.8.2
##

**Comment by AXDOOMER** [comment] 2016-08-25 02:59
sudo caja
[sudo] password for user: 

(caja:3967): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(caja:3967): GdkPixbuf-CRITICAL **: gdk_pixbuf_loader_close: assertion 'GDK_IS_PIXBUF_LOADER (loader)' failed

(caja:3967): GdkPixbuf-CRITICAL **: gdk_pixbuf_loader_get_pixbuf: assertion 'GDK_IS_PIXBUF_LOADER (loader)' failed

(caja:3967): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Not a native file, thumbnailing will likely fail
Not a native file, thumbnailing will likely fail

(caja:3967): MateDesktop-WARNING **: Error creating thumbnail for file:///home/axdoomer/.local/share/Trash/files/Screenshot_Doom_20160422_224824_zpsarr61gin.png: Fatal error reading PNG image file: Not a PNG file

(caja:3967): MateDesktop-WARNING **: Error creating thumbnail for file:///home/axdoomer/.local/share/Trash/files/Screenshot_Doom_20160422_224740_zpsaeehrlzw.png: Fatal error reading PNG image file: Not a PNG file

(caja:3967): MateDesktop-WARNING **: Error creating thumbnail for file:///home/axdoomer/.local/share/Trash/files/Screenshot_Doom_20160422_224729_zpsufniwzgz.png: Fatal error reading PNG image file: Not a PNG file
Not a native file, thumbnailing will likely fail
Not a native file, thumbnailing will likely fail
Not a native file, thumbnailing will likely fail

(caja:3967): MateDesktop-WARNING **: Unable to create loader for mime type image/vnd.microsoft.icon: Unrecognized image file format

(caja:3967): Gtk-CRITICAL **: IA__gtk_image_menu_item_set_always_show_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(caja:3967): Gtk-CRITICAL **: IA__gtk_image_menu_item_set_always_show_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(caja:3967): Gtk-CRITICAL **: IA__gtk_image_menu_item_set_always_show_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(caja:3967): Gtk-CRITICAL **: IA__gtk_image_menu_item_set_always_show_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(caja:3967): Gtk-CRITICAL **: IA__gtk_image_menu_item_set_always_show_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(caja:3967): Gtk-CRITICAL **: IA__gtk_image_menu_item_set_always_show_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(caja:3967): Gtk-CRITICAL **: IA__gtk_image_menu_item_set_always_show_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(caja:3967): Gtk-CRITICAL **: IA__gtk_image_menu_item_set_always_show_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x265d610' has no handler with id '23059'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x2bdf520' has no handler with id '21240'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x2bc1c40' has no handler with id '21247'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x2b1c860' has no handler with id '21254'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x2bc1ca0' has no handler with id '21261'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x7f7e0c039100' has no handler with id '21268'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x2ba0b00' has no handler with id '21275'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x2b8f700' has no handler with id '21282'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x2ba0a80' has no handler with id '21289'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x2b4b300' has no handler with id '21296'

(caja:3967): GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0x2b37360' has no handler with id '21303'

**Comment by AXDOOMER** [comment] 2016-08-25 03:13
The file was an EICAR text file that contained the EICAR test string and it's name was also the EICAR test string.

**Comment by monsta** [comment] 2016-09-19 10:34
Check if it happens with more recent versions of Caja.

**Comment by AXDOOMER** [comment] 2016-09-19 12:34
I deleted the file that was causing this problem. All the information that I have is posted here.

**Comment by monsta** [comment] 2016-09-19 13:05
The thing is that we don't support 1.8 these days, and there were lots of various bugs fixed since then.

**Comment by monsta** [comment] 2016-11-26 17:28
Closing for now - as we can't reproduce it in more recent versions of Caja and don't have a sample file for that.

**Closed by monsta** 2016-11-26 17:28 UTC
