### ISSUE TITLE
crash when pressing F2 without having selected file

### ISSUE THREAD

**Issue by testman42** [mate-desktop/caja#1551] opened 2021-09-12 11:23 UTC
#### Expected behaviour
Pressing F2 should either rename file or do nothing, depending on number of selected elements

#### Actual behaviour
Works as expected when one or more elements (files and/or directories) are selected, but crashes whole program (all open windows) if F2 is pressed when no elements are selected.

#### Steps to reproduce the behaviour
Open Caja window, press F2

#### MATE general version
MATE 1.24.0

#### Package version
Caja 1.24.0

#### Linux Distribution
Linux Mint 20.2 Uma 64-bit

#### Link to bugreport of your Distribution (requirement)
[linuxmint/mate](https://github.com/linuxmint/mate) doesn't have option to report issues

**Comment by lukefromdc** [comment] 2021-09-15 03:28
I wasn't able to duplicate this with locally compiled MATE 1.26.0 (including caja 1.26.0) on Debian Unstable. Pressing F2 with no files selected did nothing (as intended) or if a file was selected opened the renaming entry. Wonder what's different? Note that Mint is based on Ubuntu which in turn is based on Debian so systems should not be that far apart other than versions.

**Comment by teoso** [comment] 2021-09-21 11:40
This bug also affects me. Pressing F2 key without selected file/folder closes caja window. If multiple instances of caja are open all are terminated. Syslog contains some information on crash.

**System information**
caja: 1.24.0
MATE: 1.24.0
kernel: 5.4.0-84-generic
Linux mint 20.2 (64 bit)

**Information in syslog attached in a file.**

[syslog information on systemd-coredump.txt](https://github.com/mate-desktop/caja/files/7202721/syslog.information.on.systemd-coredump.txt)

**Comment by flth** [comment] 2022-01-17 12:47
Was going to report the same. Linux Mint Mate edition, even can try it in the live system. Start it up, open home folder, press F2 and it closes.

**Comment by mbkma** [comment] 2022-01-17 14:10
Please provide information if this happens on Caja 1.26.

**Comment by lukefromdc** [comment] 2022-01-18 01:27
I do not get this crash with caja 1.26 from git master over Debian Unstable with
locally built GTK 3.24.30 and glib 2.70.0

**Comment by adminquest** [comment] 2022-01-27 10:56
On my site it works fine with DebianSID with mate-desktop (1.26.0-1)

**Comment by smurphos** [comment] 2022-07-06 03:57
Can be reproduced with 1.26 in Mint 20.3 - F2 with no selection segfaults caja.

**Comment by lukefromdc** [comment] 2022-07-06 04:04
Still cannot duplicate this with locally compiled caja 1.26.0 from git master on Debian Unstable w locally compiled gtk 3.24.34 and locally compiled libglib 2.72.1. Wondering what is different

**Comment by smurphos** [comment] 2022-07-06 04:33
Mint 21 based on Ubuntu 22.04 in beta should be available in the next week or - if it still occurs there (still 1.26.0) I'll raise it during the beta test. It does look like Mint are making some minor mods to the Ubuntu packaged version for the Mint package, specifically support for Mint's 'bulky' mass rename utility. I suspect that could be the difference.

**Comment by smurphos** [comment] 2022-07-06 05:01
OK - bulky is definitely the culprit. Caja doesn't segfault if bulky is uninstalled, does with it installed.

**Comment by cristian64** [comment] 2023-05-06 22:13
The crash can still be reproduced with Linux Mint 21.1 "Vera":

**Reproduction steps:**

- Launch Caja.
- Press `F2` without selecting any file.

In my case, I see this crash several times a day: a misclick before pressing `F2`, and thus failing to select the file, and Caja vaporizes.

**Comment by lukefromdc** [comment] 2023-05-07 06:29
Closing as Bulky has been identifed as the culprit, and an issue opened there:
https://github.com/linuxmint/bulky/issues/43

**Closed by lukefromdc** 2023-05-07 06:29 UTC
