### ISSUE TITLE
new 1.23.1: test suite core dumps

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/caja#1250] opened 2019-07-01 21:52 UTC
I know that it needs $DISPLAY however I found that it core dumps.

<pre>[tkloczko@barrel SPECS]$ rpm -q glib2 gtk3
glib2-2.61.1-3.fc31.x86_64
gtk3-3.24.9-2.fc31.x86_64
</pre>

<pre>+ /usr/bin/make -O -j48 V=1 VERBOSE=1 check
Making check in eel
/usr/bin/make  check-am
/usr/bin/make  check-TESTS
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.1/eel&apos;
FAIL: check-eel
make[4]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.1/eel&apos;
make[4]: *** [Makefile:936: test-suite.log] Error 1
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.1/eel&apos;
=====================================
   caja 1.23.1: eel/test-suite.log
=====================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: check-eel
===============
</pre>

<pre>[tkloczko@barrel SPECS]$ coredumpctl list | tail -1
Mon 2019-07-01 22:47:09 BST   45488  1000  1000   5 present   /home/tkloczko/rpmbuild/BUILD/caja-1.23.1/eel/check-program
[tkloczko@barrel SPECS]$ coredumpctl gdb /home/tkloczko/rpmbuild/BUILD/caja-1.23.1/eel/check-program
           PID: <b>45488</b> (check-program)
           UID: 1000 (tkloczko)
           GID: 1000 (tkloczko)
        Signal: 5 (TRAP)
     Timestamp: Mon 2019-07-01 22:47:08 BST (3min 28s ago)
  Command Line: ./check-program --g-fatal-warnings --sm-disable
    Executable: <b>/home/tkloczko/rpmbuild/BUILD/caja-1.23.1/eel/check-program</b>
 Control Group: /user.slice/user-1000.slice/session-14.scope
          Unit: session-14.scope
         Slice: user-1000.slice
       Session: 14
     Owner UID: 1000 (tkloczko)
       Boot ID: 9ab00058f1414c4ea9a34cb8b5268843
    Machine ID: 0594d5138b9d4b6fafc8fd1fb24e12d2
      Hostname: barrel
       Storage: /var/lib/systemd/coredump/core.check-program.1000.9ab00058f1414c4ea9a34cb8b5268843.45488.1562017628000000.lz4
       Message: Process 45488 (check-program) of user 1000 dumped core.
                
                Stack trace of thread 45488:
                #0  0x00007f326986a7b5 _g_log_abort (libglib-2.0.so.0)
                #1  0x00007f326986e2cc g_log_writer_default (libglib-2.0.so.0)
                #2  0x00007f326986a854 g_log_structured_array (libglib-2.0.so.0)
                #3  0x00007f326986ab21 g_log_structured_standard (libglib-2.0.so.0)
                #4  0x00007f3269f107ad gtk_init (libgtk-3.so.0)
                #5  0x0000560d87a86596 n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.23.1/eel/check-program)

<font color="#75507B"><b>GNU gdb (GDB) Fedora 8.3.50.20190625-18.fc31</b></font>
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type &quot;show copying&quot; and &quot;show warranty&quot; for details.
This GDB was configured as &quot;x86_64-redhat-linux-gnu&quot;.
Type &quot;show configuration&quot; for configuration details.
For bug reporting instructions, please see:
&lt;http://www.gnu.org/software/gdb/bugs/&gt;.
Find the GDB manual and other documentation resources online at:
    &lt;http://www.gnu.org/software/gdb/documentation/&gt;.

For help, type &quot;help&quot;.
Type &quot;apropos word&quot; to search for commands related to &quot;word&quot;...
Reading symbols from <font color="#4E9A06">/home/tkloczko/rpmbuild/BUILD/caja-1.23.1/eel/check-program</font>...
[New LWP 45488]
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/lib64/libthread_db.so.1&quot;.
Core was generated by `./check-program --g-fatal-warnings --sm-disable&apos;.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  <font color="#C4A000">_g_log_abort</font> (<font color="#06989A">breakpoint</font>=1) at <font color="#4E9A06">../glib/gmessages.c</font>:554
554	../glib/gmessages.c: No such file or directory.
Missing separate debuginfos, use: dnf debuginfo-install at-spi2-atk-2.33.2-2.fc31.x86_64 at-spi2-core-2.33.2-2.fc31.x86_64 atk-2.33.3-2.fc31.x86_64 bzip2-libs-1.0.7-2.fc31.x86_64 cairo-1.16.0-5.fc31.x86_64 cairo-gobject-1.16.0-5.fc31.x86_64 dbus-libs-1.12.16-1.fc31.x86_64 dconf-0.32.0-2.1.fc31.x86_64 fontconfig-2.13.91-2.fc31.x86_64 freetype-2.10.0-2.3.fc31.x86_64 fribidi-1.0.5-3.1.fc31.x86_64 gdk-pixbuf2-2.38.1-2.1.fc31.x86_64 glibc-2.29.9000-30.fc31.x86_64 graphite2-1.3.10-7.fc30.x86_64 libX11-1.6.8-3.fc31.x86_64 libX11-xcb-1.6.8-3.fc31.x86_64 libXau-1.0.9-2.1.fc31.x86_64 libXcomposite-0.4.4-17.fc31.x86_64 libXdamage-1.1.4-16.fc30.x86_64 libXdmcp-1.1.3-2.1.fc31.x86_64 libXext-1.3.4-2.1.fc31.x86_64 libXfixes-5.0.3-9.fc30.x86_64 libXi-1.7.10-2.fc31.x86_64 libXinerama-1.1.4-4.fc31.x86_64 libXrandr-1.5.2-2.1.fc31.x86_64 libXrender-0.9.10-10.1.fc31.x86_64 libblkid-2.34-2.fc31.x86_64 libepoxy-1.5.3-3.fc31.x86_64 libffi-3.2.1-2.1.fc31.x86_64 libgcrypt-1.8.4-4.1.fc31.x86_64 libgpg-error-1.36-2.fc31.x86_64 libmount-2.34-2.fc31.x86_64 libselinux-2.9-3.fc31.x86_64 libthai-0.1.28-2.fc30.x86_64 libwayland-client-1.17.0-2.1.fc31.x86_64 libwayland-cursor-1.17.0-2.1.fc31.x86_64 libxcb-1.13.1-3.1.fc31.x86_64 libxml2-2.9.9-3.1.fc31.x86_64 lz4-libs-1.9.1-2.fc31.x86_64 mate-desktop-libs-1.23.1-2.fc31.x86_64 pango-1.43.0-4.1.fc31.x86_64 pixman-0.38.4-2.1.fc31.x86_64 startup-notification-0.12-18.fc31.x86_64 systemd-libs-242-5.git7a6d834.fc31.x86_64 xcb-util-0.4.0-13.1.fc31.x86_64 xz-libs-5.2.4-6.1.fc31.x86_64 zlib-1.2.11-15.fc30.x86_64
(gdb) bt full
#0  <font color="#3465A4">0x00007f326986a7b5</font> in <font color="#C4A000">_g_log_abort</font> (breakpoint=1) at <font color="#4E9A06">../glib/gmessages.c</font>:554
        debugger_present = 1
#1  <font color="#3465A4">0x00007f326986e2cc</font> in <font color="#C4A000">g_log_writer_default</font> (log_level=18, 
    log_level@entry=G_LOG_LEVEL_WARNING, fields=fields@entry=0x7ffe786f69c0, n_fields=n_fields@entry=6, user_data=user_data@entry=0x0) at <font color="#4E9A06">../glib/gmessages.c</font>:2690
        __FUNCTION__ = &quot;g_log_writer_default&quot;
        initialized = 1
        stderr_is_journal = 0
#2  <font color="#3465A4">0x00007f326986a854</font> in <font color="#C4A000">g_log_structured_array</font> (log_level=G_LOG_LEVEL_WARNING, fields=0x7ffe786f69c0, n_fields=6) at <font color="#4E9A06">../glib/gmessages.c</font>:1923
        writer_func = 0x7f326986e150 &lt;g_log_writer_default&gt;
        writer_user_data = 0x0
        recursion = 0
        depth = 1
#3  <font color="#3465A4">0x00007f326986ab21</font> in <font color="#C4A000">g_log_structured_standard</font>
    (log_domain=log_domain@entry=0x7f326a07c20f &quot;Gtk&quot;, log_level=log_level@entry=G_LOG_LEVEL_WARNING, file=file@entry=0x7f326a0ac233 &quot;gtkmain.c&quot;, line=line@entry=0x7f326a0ac306 &quot;1166&quot;, func=func@entry=0x7f326a0aca70 &lt;__func__.45702&gt; &quot;gtk_init&quot;, message_format=message_format@entry=0x7f326a0ac2ee &quot;cannot open display: %s&quot;)
    at <font color="#4E9A06">../glib/gmessages.c</font>:1980
        fields = 
            {{key = 0x7f3269901987 &quot;PRIORITY&quot;, value = 0x7f32698a86ae, length = -1}, {key = 0x7f3269901990 &quot;CODE_FILE&quot;, value = 0x7f326a0ac233, length = -1}, {key = 0x7f326990199a &quot;CODE_LINE&quot;, value = 0x7f326a0ac306, length = -1}, {key = 0x7f32699019a4 &quot;CODE_FUNC&quot;, value = 0x7f326a0aca70 &lt;__func__.45702&gt;, length = -1}, {key = 0x7f32698f6af1 &quot;MESSAGE&quot;, value = 0x560d888d7c30, length = -1}, {key = 0x7f32699019e1 &quot;GLIB_DOMAIN&quot;, value = 0x7f326a07c20f, length = -1}}
        n_fields = 6
        message_allocated = 0x560d888d7c30 &quot;cannot open display: &quot;
        buffer = &quot;\000\000\000\000\000\000\000\000$\220Vj2\177\000\000\000\000\000\000\000\000\000\000t9\217\210\rV&quot;, &apos;\000&apos; &lt;repeats 11 times&gt;, &quot;\216\020\276\022x\020\317@kox\376\177\000\000\360\265Pj2\177&quot;, &apos;\000&apos; &lt;repeats 18 times&gt;, &quot;\310kox\376\177\000\000\060kox\376\177\000\000\260Ҏ\210\rV\000\000\273aPj2\177\000\000\001&quot;, &apos;\000&apos; &lt;repeats 16 times&gt;, &quot;kox\376\177\000\000\300Ҏ\210\rV\000\000\001\000\000\000\000\000\000\000\340kox\376\177\000\000\200kox\376\177\000\000\000\000\000\000\000\000\000\000\340kox\376\177\000\000\320kox\376\177\000\000\310kox\376\177\000\000\rތ&quot;...
        args = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffe786f6f38, reg_save_area = 0x7ffe786f6e60}}
#4  <font color="#3465A4">0x00007f3269f107ad</font> in <font color="#C4A000">gtk_init</font> (argc=&lt;optimized out&gt;, argv=&lt;optimized out&gt;) at <font color="#4E9A06">gtkmain.c</font>:1164
        display_name_arg = &lt;optimized out&gt;
        __func__ = &quot;gtk_init&quot;
#5  <font color="#3465A4">0x00007f3269f107ad</font> in <font color="#C4A000">gtk_init</font> (argc=&lt;optimized out&gt;, argv=&lt;optimized out&gt;) at <font color="#4E9A06">gtkmain.c</font>:1159
        __func__ = &quot;gtk_init&quot;
#6  <font color="#3465A4">0x0000560d87a86596</font> in <font color="#C4A000">main</font> (argc=&lt;optimized out&gt;, argv=&lt;optimized out&gt;) at <font color="#4E9A06">check-program.c</font>:45
(gdb) 
</pre>

**Comment by lukefromdc** [comment] 2019-07-02 04:28
On installed caja from current git master, running` caja -c` yields a successful completion of that round of self-checks. On the build directory however, running `make check` does indeed fail with
```

FAIL: check-eel
============================================================================
Testsuite summary for caja 1.23.1
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See eel/test-suite.log
Please report to https://mate-desktop.org
============================================================================
make[4]: *** [Makefile:929: test-suite.log] Error 1
make[4]: Leaving directory '/home/luke/Desktop/Development/MATE_Development_Work/caja_1.23.1+git20190701/eel'
make[3]: *** [Makefile:1037: check-TESTS] Error 2
make[3]: Leaving directory '/home/luke/Desktop/Development/MATE_Development_Work/caja_1.23.1+git20190701/eel'
make[2]: *** [Makefile:1110: check-am] Error 2
make[2]: Leaving directory '/home/luke/Desktop/Development/MATE_Development_Work/caja_1.23.1+git20190701/eel'
make[1]: *** [Makefile:1112: check] Error 2
make[1]: Leaving directory '/home/luke/Desktop/Development/MATE_Development_Work/caja_1.23.1+git20190701/eel'
make: *** [Makefile:501: check-recursive] Error 1
luke@ubuntu:~/Desktop/Development/MATE_Development_Work/caja_1.23.1+git20190701$ 
```
On `make  V=1 VERBOSE=1 check` the relevant part of the error message seems to be this:
```
running eel_self_check_string
munmap_chunk(): invalid pointer
Aborted
FAIL check-eel (exit status: 134)
```
Is this just that display issue mentioned above (I have never tried the build time checks before as I did not know about them) and incorrect invocation of the tests, or a new problem in Caja itself?

**Comment by raveit65** [comment] 2019-07-02 08:13
Problems is introduced between 1.22 and 1.23. I am closing this because double posting isn't allowed.
https://github.com/mate-desktop/caja/issues/1250

**Comment by raveit65** [comment] 2019-07-02 08:18
Hmm, for some reasons i can#t re-open to report.
Any way you ignore our template again!!

**Comment by raveit65** [comment] 2019-07-02 08:19
Sorry, i don't work on reports if user ignore templates.

**Comment by vkareh** [comment] 2019-07-16 02:39
This works fine for me in Ubuntu 19.04 (see below), and the issue is not described well, so I really don't know what I'm looking for here? @lukefromdc - can you still reproduce after doing a `make clean && ./configure ...`? Otherwise we should probably close this until someone can explain what this bug is about...
```
$ make -j7 V=1 VERBOSE=1 check
Making check in po
Making check in eel
PASS: check-eel
============================================================================
Testsuite summary for caja 1.23.1
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in libcaja-extension
Making check in libegg
Making check in libcaja-private
Making check in src
Making check in file-manager
PASS: check-caja
============================================================================
Testsuite summary for caja 1.23.1
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in test
Making check in data
Making check in icons
Making check in patterns
Making check in icons
Making check in docs
Making check in reference
Making check in libcaja-extension
```

**Comment by lukefromdc** [comment] 2019-07-16 19:09
As of now (assuming I have https://github.com/mate-desktop/caja/pull/1259 applied so the build can finish), the checks now finish clean with no errors, same as above

**Comment by lukefromdc** [comment] 2019-07-16 19:10
This was fixed by https://github.com/mate-desktop/caja/pull/1251

**Closed** 2019-07-17 09:55 UTC
Labels: template ignored!
