### ISSUE TITLE
Can no longer "restore" or "undo" files sent to trash after recent commits

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#468] opened 2015-09-28 23:01 UTC
After building caja with these two commits:

b1e9a7fe429546105ffda8424cc5719a13e8a295 
use standard defines for "trash::" attributes  

f8ed2af9510cb20f2ad8101aeaab5c6458ade0d7  
undostack: don't try restoring files w/o "trash::orig-path" attribute 

it is no longer possible to undo sending a file to the trash, nor to select and restore it. The error that results is one showing the former location is unknown

**Comment by monsta** [comment] 2015-09-29 09:18
1. Which distro/release?
2. Try to build w/o one or both commit and see what happens (possibly a crash).

**Comment by lukefromdc** [comment] 2015-09-29 17:16
This is on Debian Unstable, built locally with gtk3

**Comment by lukefromdc** [comment] 2015-09-29 18:12
Rolling back  libcaja-private/caja-undostack-manager.c to the version used in the first of the two
commits affecting the trash:

https://github.com/mate-desktop/caja/commit/b1e9a7fe429546105ffda8424cc5719a13e8a295

causes a crash on an attempt to undo sending a file to the trash, on an attempt to restore a file
from the trash generates the same "could not determine location" "the item cannot be restored 
from trash" error. Only manually dragging the file back works, that has never been broken.

Caja's trash feature worked without issue (at least in gtk3) up until this commit. The version of caja
I had build from the last commit before the one above had no problems with the trash.

**Comment by monsta** [comment] 2015-09-30 10:49
That's it, you've hit that annoying bug in gvfs: 
https://bugs.launchpad.net/bugs/1495943

I don't have any Debian Sid installations, and it's not reproducible in Testing, so I could only reproduce it in Ubuntu 15.10. Did you use glib or gvfs from Experimental, by any chance?

As for these last commits, they were pushed to prevent Caja from crashing when ```trash::orig-path``` attribute isn't set for the file you try to restore (https://github.com/mate-desktop/caja/issues/361).

**Comment by monsta** [comment] 2015-09-30 10:52
Looks like the root cause is actually in glib >= 2.45, see [upstream bug report](https://bugzilla.gnome.org/show_bug.cgi?id=749314).

**Comment by lukefromdc** [comment] 2015-09-30 18:33
I've got glib2.0 2.46.0-1, which is in unstable. This kind of bug gives 
two options: wait out the upstream bug, or find a workaround to bypass
it. In this case, glib might be fixed well before caja 1.12 gets released.
Ubuntu just upgraded this bug to "critical" hopefully  implying either they 
will fix it or someone else will. This might actually hold up the release of
Ubuntu Wily after all.

Also, this turns what for some (not for me) was a crasher into a requirement
to manually restore anything from trash, an acceptable tradeoff.

**Comment by monsta** [comment] 2015-10-01 09:17
I think we can hope for the upstream fix for 2.46.x - the devs are working on it and trying some patches (see the upstream report). Can you please file a bug report in Debian BTS? You can use the same steps to reproduce as in that Ubuntu bug.

**Comment by lukefromdc** [comment] 2015-10-01 17:58
This has already gone upstream from Debian or any other distro, the ubuntu
bug just got assigned to gnome-bugs at:

https://bugzilla.gnome.org/show_bug.cgi?id=749314

it is in the "needs info" category from the original poster. Also, I just verified
that Nemo is also affected by this, the bugzilla lists it as a bug in glib 2.46
with Nautilus as affected by it.

For some reason the older version of caja did not hit this bug-but I hear that
was crashy for some other people.

**Comment by lukefromdc** [comment] 2015-10-01 18:01
The GNOME bugzilla also lists this patch that someone tested with 
success on Fedora Rawhide:

https://bugzilla.gnome.org/attachment.cgi?id=312363&action=diff

Hopefully this or something similar will soon come out as a fix, as this
is now confirmed to affect Caja, Nemo, and Nautilus.

**Comment by monsta** [comment] 2015-10-02 12:29
Since this is not our issue (and also on the same subject as https://github.com/mate-desktop/caja/issues/361), I'm closing it. There's nothing we can do here but wait for glib fix.

**Closed by monsta** 2015-10-02 12:29 UTC
Labels: unconfirmed

**Comment by lukefromdc** [comment] 2015-10-02 22:28
FIne by me
