### ISSUE TITLE
Crazy big symbols + can't uncheck icons set from Thunar - 1.12.6 GTK3

### ISSUE THREAD

**Issue by kolorafa** [mate-desktop/caja#556] opened 2016-05-26 17:04 UTC
Crazy big symbols - 1.12.6 GTK3

![snapshot-2016-05-26-18-57-34](https://cloud.githubusercontent.com/assets/921517/15582956/d4ba3418-2373-11e6-9c31-79bd8c866900.png)

Can't uncheck symbols (symbols was set before caja was installed, thunar still installed, can be uncheck by thunar):

![snapshot-2016-05-26-18-58-21](https://cloud.githubusercontent.com/assets/921517/15582993/fde6061e-2373-11e6-8863-a1cdbc6aa156.png)

If checked - double icons :)

![snapshot-2016-05-26-19-00-25](https://cloud.githubusercontent.com/assets/921517/15583032/29cd299c-2374-11e6-9f69-ec500f0fe16e.png)
##

**Comment by raveit65** [comment] 2016-05-26 17:47
Wrong desktop......we don't ship thunar!

**Comment by kolorafa** [comment] 2016-05-27 06:14
This is not wrong desktop, this app on screenshots is Caja

I'm telling that those Icons was set in Thunar (that i did use before Caja)

But the problem with big icons and unable to uncheck icons is in caja!

**Comment by flexiondotorg** [comment] 2017-01-17 22:53
Duplicate of #664

**Closed by flexiondotorg** 2017-01-17 22:53 UTC
