### ISSUE TITLE
starting file manager loop

### ISSUE THREAD

**Issue by lpedraza** [mate-desktop/caja#407] opened 2015-04-20 21:42 UTC
Hi guys,

I am problem running the LM 17. The file manager not start and i will get a loop in my toolbar desktop with the message "Starting file manager". I can't navigate into my files.

Thanks
![screenshot-1](https://cloud.githubusercontent.com/assets/6947215/7241113/f0a0f24e-e78c-11e4-846a-f4fceaeac682.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/6947215/7241123/0b59220a-e78d-11e4-80df-f5e504f5c3e0.png)

**Comment by monsta** [comment] 2015-12-10 18:58
Does it still happen in Mint 17.3?

**Comment by monsta** [comment] 2016-01-26 18:42
Well, if there won't be any more feedback we can't do anything but close this. It might as well be fixed in the latest version.

**Comment by raveit65** [comment] 2016-01-26 18:59
@monsta 
only for your info, i have a actual report in fedora about.

**Comment by monsta** [comment] 2016-01-26 19:13
Oops, looks like I've pushed the close button instead of just commenting. I was going to give it some more time for possible feedback.
If it still happens it should be reopened...

**Comment by raveit65** [comment] 2016-01-30 17:26
Yesterday i ran in this issue in a f24 (rawhide) VM but i could track down the issue. What i did?
1. Updated a mate gtk2 installation to gtk3
2. removed installed caja-terminal package
 (external python caja extension which shows a embedded terminal inside caja), and isn't ported to gtk3.
3 . restart the session and i get this loop of starting caja windows. Same with starting caja from terminal or menu.
4. Stacktrace shows that it is a problem with loading extensions.
5. removing python-caja solved the issue here, so the problem is somewhere in python-caja.
```
Thread 1 (Thread 0x7f42a3514a80 (LWP 1684)):
#0  0x00007f429f9761eb in g_type_check_instance_cast (type_instance=0x5650c8f12330, iface_type=80) at gtype.c:4066
        node = 0x440
        iface = <optimized out>
        is_instantiatable = <optimized out>
#1  0x00005650c757c017 in caja_extensions_get_for_type ()
#2  0x00005650c7590d96 in caja_file_invalidate_extension_info_internal ()
```
full stacktrace at https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/backtrace-caja

**Comment by monsta** [comment] 2016-01-30 17:35
Yes, I get the same problem with python-caja in GTK+3. I had to disable that extension for now.

However, we don't know what caused Caja crashes in reporter's installation (which is apparently GTK+2). The "loop" itself isn't a cause, it's an effect of Caja crashing shortly after start + session manager restarting it.

**Comment by raveit65** [comment] 2016-01-30 17:46
Btw, here is my downstream report.
https://bugzilla.redhat.com/show_bug.cgi?id=1291540

**Comment by monsta** [comment] 2016-01-30 18:13
Oh that's quite a lot of info, thanks. Backtrace is different but ends up in the same function (```caja_extensions_get_for_type```)...

Oh BTW... your backtrace is missing Caja's own debug info (no source file names, line numbers, variables lists, etc.) :smile:

**Comment by monsta** [comment] 2016-01-30 18:32
@alexandervdm: can you please take a look at this? It always crashes at:
https://github.com/mate-desktop/caja/blob/master/libcaja-private/caja-extensions.c#L175

**Comment by raveit65** [comment] 2016-01-30 18:50
> Oh BTW... your backtrace is missing Caja's own debug info (no source file names, line numbers, variables lists, etc.) :smile:

stacktrace with caja-debuginfo installed
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/backtrace-caja-2

**Comment by monsta** [comment] 2016-02-05 08:21
@lpedraza: we can't reproduce it, so we need some more info to figure out what's going on. Please post the output of these commands:

- ```ls -l /run/user/1000/dconf/user```
- ```ls -l /usr/share/caja-python/extensions```
- ```ls -l /usr/lib/x86_64-linux-gnu/caja/extensions-2.0``` (if you have 64-bit system) or
```ls -l /usr/lib/i386-linux-gnu/caja/extensions-2.0``` (if you have 32-bit system)
- ```gsettings get org.mate.caja.extensions disabled-extensions```

**Comment by monsta** [comment] 2016-02-05 12:08
I think https://github.com/mate-desktop/caja/commit/3d29330d2eaca9ac890bdbb10c42e8df73ba1b87 might fix it - at least it fixes the crash with python-caja in GTK+3 build for me.

**Comment by raveit65** [comment] 2016-02-05 12:57
Looks like i will get an answer in upstream report the next days, see last post.
And i will test the fix for gtk3.

**Comment by monsta** [comment] 2016-02-05 18:27
In the meanwhile, you can make a patch from that commit for them to test. It should apply cleanly in 1.12.

**Comment by raveit65** [comment] 2016-02-06 13:02
Seems to working fine with caja-1.13, but i couldn't reproduce the bug anymore w/o this commit i a gtk3 rawhide VM(vbox). I deleted the other VM (qemu-kvm) where i created the stacktrace to save diskspace.
For fedora rawhide i have to use vbox to avoid annoying gtk3 magnifying glass.

**Comment by monsta** [comment] 2016-02-15 14:19
Possible fix is now released in 1.12.4.

**Comment by raveit65** [comment] 2016-02-19 09:03
I looks like that the issue is fixed, i got one feedback :)
https://bugzilla.redhat.com/show_bug.cgi?id=1291540#c32

**Comment by monsta** [comment] 2016-03-25 08:11
Ok, I guess it's indeed fixed, no more feedback about the problem happening.

**Closed by monsta** 2016-03-25 08:11 UTC
Labels: unconfirmed
