### ISSUE TITLE
trash can not working in FreeBSD 10.2

### ISSUE THREAD

**Issue by extremelydangerous** [mate-desktop/caja#458] opened 2015-09-10 03:57 UTC
caja release 1.10.3 on FreeBSD Version 10.2 Amd64, does not work, you drag a file into the trash can, the file is moved to the .local/share/Trash/files, information is written into the info directory but the trash icon shows empty. So the options in the trash properties shows as the trash is empty too.

**Comment by monsta** [comment] 2016-03-30 18:43
@obache: maybe you could check it? We really could use more testers from *BSD land here... and all of us developers use Linux, so we can't reproduce such issues right away.

**Comment by obache** [comment] 2016-03-31 05:55
Something wrong on NetBSD 7.0 too.

I could reproduce the situation at the first time.
After did "Move to Trash" an another file,  "Trash" icon seemed to be as "not empty".
I could open "Trash" and could do "Restore ... from Trash" for a file, but couldn't do the second file due to
"Could not determine original location of ...".
After restarted the MATE session, it might be seemed well, or might be seemd infinity "hourgrass".

**Comment by obache** [comment] 2016-03-31 09:36
But it may come from my too old gvfs.

**Comment by extremelydangerous** [comment] 2016-04-04 04:36
Em Qua, 2016-03-30 às 11:43 -0700, monsta escreveu:
> @obache: maybe you could check it? We really could use more testers
> from *BSD land here... and all of us developers use Linux, so we
> can't reproduce such issues right away.
An update to gtk bump to gtk 2.24.29  solved the problem... now caja
works...
We are heavy users of MATE... it is wonderfull...  we user Mate as the
desktop OS for large servers
that uses virtualbox to run windows 2003, 2008 and 2012  in virtual
environments
Mate is also used in diskless  stations..  You can install the 1.2GB
full mate desktop in less than one hour in the internet.
I can give you a vnc account to test the real thing.. 
take a look at the BSD desktop images => http://www.k1.com.br/screensho
ts

**Comment by monsta** [comment] 2016-04-04 13:58
I suspect gvfs update was around there too. It shouldn't be just GTK+.

**Comment by obache** [comment] 2016-05-08 11:03
Works fine here too, with old gvfs.
I have GTK2+ 2.24.30 now, and even rollbacked to 2.24.28, I cannot reproduce the issue.
Additionally, caja on FreeBSD ports was updated to 1.12.4 at 01 Apr 2016.
So probably something else might be the triger, and not the issue in latest caja release.

**Comment by monsta** [comment] 2016-05-13 11:46
Ok guys, thanks for the feedback. Since it seems to be solved, I'm closing it. We can always reopen if the issue comes back.

**Closed by monsta** 2016-05-13 11:46 UTC
Labels: unconfirmed
