### ISSUE TITLE
Caja doesn't always focus tab on drag hover

### ISSUE THREAD

**Issue by git-oliver** [mate-desktop/caja#39] opened 2012-10-31 20:07 UTC
Two years ago I found this bug in Nautilus 2.32 and reported it on gnome.org. Last month it has been fixed, but only in git master of GTK+ and Nautilus. I don't know the code of GTK2 and 3 well enough to backport the patches in the near future. So instead I open this report so that others can help.

Details of this bug and its fixes for Nautilus and GTK+ can be found here: https://bugzilla.gnome.org/show_bug.cgi?id=635485

**Comment by NiceandGently** [comment] 2015-05-19 14:50
@monsta 
please close

**Comment by monsta** [comment] 2015-06-04 19:09
Well, some testing showed us that the issue is purely cosmetic.
Even if Caja doesn't switch focus on another tab, the drag-n-drop operation completes successfully anyway. That is, the file gets copied/moved. So this is not a critical issue. And since the issue is upstream (as described above), I'm closing it.

**Closed by monsta** 2015-06-04 19:09 UTC

**Comment by git-oliver** [comment] 2015-06-15 21:55
I don't agree that it is purely cosmetic - or solved.
Drag-n-drop to a tab itself works fine. But this bug is about "changing the tab while dragging" (a quite advanced feature, I confess). Caja 1.8.2 in Mint 17.1 still behaves erratic, which is not good for fragile drag-n-drop operations.

As I understand there is a fix. But it was never released as Gtk+ 2. Isn't there a place in MATE for such Gtk+ 2 patches?

**Comment by monsta** [comment] 2015-06-16 09:03
> Isn't there a place in MATE for such Gtk+ 2 patches?

Shipping GTK+ patches with MATE? For all distros? I can't even imagine that :)

**Comment by git-oliver** [comment] 2015-06-16 10:07
Ok. I didn't know that MATE is based on the unchanged GTK+ 2. I thought MATE contains already parts of GTK, including patches.

Does anybody know if there is a sign or chance that Caja will be ported to GTK+ 3 then?

**Comment by NiceandGently** [comment] 2015-06-16 15:03
there are experimental repos for mate GTK3 for fedora an archlinux.
http://mate-desktop.org/blog/2015-06-11-mate-1-10-released/
