### ISSUE TITLE
Too many files in a folder

### ISSUE THREAD

**Issue by magiclen** [mate-desktop/caja#412] opened 2015-05-07 16:37 UTC
I have many log files(more than 40000) and store them into a folder named 'logs'. When I use caja to browser this folder, caja always crashes because of the large files count.

**Comment by monsta** [comment] 2016-03-30 13:31
Well, I've created 40000 empty files:
```
for i in {1..40000}; do touch test-$i.txt; done
```
but couldn't reproduce the crash.

Can you try to obtain a backtrace via gdb?

**Comment by magiclen** [comment] 2016-03-30 14:06
Sorry, I use Cinnamon now.

**Comment by monsta** [comment] 2016-03-30 17:42
Ok, I'll close it then. If anyone confirms it later, we can reopen it.

**Closed by monsta** 2016-03-30 17:42 UTC
Labels: unconfirmed
