### ISSUE TITLE
Latest release: plural forms dropped in FR and OC at least

### ISSUE THREAD

**Issue by Mejans** [mate-desktop/caja#1645] opened 2022-07-04 09:47 UTC
#### Expected behaviour
The translations form Transifex are imported

#### Actual behaviour
The translations are imported but at least for French and Occitan when there is a pluralization, the old translations are dropped and the strings get untranslated.

#### Steps to reproduce the behaviour
See the commit and seek fr.po and oc.fr

**Comment by raveit65** [comment] 2022-08-06 16:14
Because this bogus translation causes compiling issues.
**Please do not add broken syntax in translations strings at transifex.**
I don't speak french in result i can't fix the string and i have to delete them for making a release.
Issue caused by translators, closing.

**Closed by raveit65** 2022-08-06 16:14 UTC

**Comment by Mejans** [comment] 2022-08-17 10:04
I don't know where to see these messages.
For other translator, paste this in the filter field : text:%\'d translation_text_not_contains:%\'d
