### ISSUE TITLE
Caja crashing after spewing GTK errors

### ISSUE THREAD

**Issue by frankzen** [mate-desktop/caja#634] opened 2016-09-09 23:50 UTC
Reference: bug number 836669 on debian.org.

Segfaults on my Debian stretch/sid system  but only seemingly when opening a directory. Other apps on the desktop which Caja manages seems to be fine...despite the hundreds of gtk errors in the  .xsession-errors file

(mate-panel:5280): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate MatePanelAppletContainer's child GtkSocket 0x7f8dbc014800. Allocation is 201x30, but minimum required size is 400x30.

(mate-panel:5280): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate PanelWidget's child MatePanelAppletFrameDBus 0x56022ae05b90. Allocation is 100x30, but minimum required size is 100x32.

(mate-panel:5280): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate PanelWidget's child MatePanelAppletFrameDBus 0x56022ae055f0. Allocation is 228x30, but minimum required size is 228x34.

(mate-panel:5280): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate PanelWidget's child MatePanelAppletFrameDBus 0x56022ae05230. Allocation is 40x30, but minimum required size is 40x34.

(mate-panel:5280): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate PanelWidget's child MatePanelAppletFrameDBus 0x56022ae05b90. Allocation is 100x30, but minimum required size is 100x32.

(mate-panel:5280): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate PanelWidget's child MatePanelAppletFrameDBus 0x56022ae055f0. Allocation is 228x30, but minimum required size is 228x34.

(marco:5262): Gtk-WARNING **: MetaFrames 0x560d25286130 is drawn without a current allocation. This should not happen.

(marco:5262): Gtk-WARNING **: MetaFrames 0x560d25286130 is drawn without a current allocation. This should not happen.

(marco:5262): Gtk-WARNING **: MetaFrames 0x560d25286130 is drawn without a current allocation. This should not happen.

(marco:5262): Gtk-WARNING **: MetaFrames 0x560d25286130 is drawn without a current allocation. This should not happen.

(marco:5262): Gtk-WARNING **: MetaFrames 0x560d25286130 is drawn without a current allocation. This should not happen.

**Comment by lukefromdc** [comment] 2016-09-10 00:30
This is with Caja 1.14 as shipped b Debian? That version is not
compatable with GTK 3.21.5. Debian updated GNOME to version
3.21.91, which pulls in GTK 3.21.5 but did not update MATE, in 
which Caja and mate-settings-daemon must also be updated to
developmeent versions in order to work. 

The segfaults are caused by the "information" sidebar
which was fixed with 1.15.0, and the desktop redraw issue was fixed
in 1.15.4, the current development version. 

Many GTK errors have been stopped in Caja git master, also since 
GTK 3.20 a LOT of programs not just from MATE have spewed
warnings.

For now you have two options to get MATE working until 1.16 ships
and Debian picks it up: roll back GTK3 to version 3,.20 (which will
force uninstallation of GNOME) or use these two packages offered 
at
https://archive.org/details/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme

https://archive.org/download/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme/caja-gtk3.22_1.15.4-11uke1_amd64.deb
https://archive.org/download/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme/mate-settings-daemon-gtk3.22_1.15.1git20160804-1luke1_amd64.deb

Those links are good now, if the packages are superseded the links will break but
the newer replacements will be at the same website and these packages will move
to the "older versions" directory there.

**Comment by raveit65** [comment] 2016-09-10 05:53
Mate debian Maintainers have decided not to use 1.15 packages from us, so file out a but against debian bug reporting system an wake up those guys..

**Closed by raveit65** 2016-09-10 05:53 UTC

**Comment by sc0w** [comment] 2016-09-11 22:48
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836669

https://sunweavers.net/blog/node/45
