### ISSUE TITLE
Feature request: ACLs

### ISSUE THREAD

**Issue by ge79so** [mate-desktop/caja#408] opened 2015-04-23 08:47 UTC
Please could you support ACLs in the permissions tab, if configured?

**Comment by fingus** [comment] 2015-04-27 06:46
would be very great! a tool for that would be eiciel (http://rofi.roger-ferrer.org/eiciel/) like this:
![Example from webpage](http://rofi.roger-ferrer.org/eiciel/gfx/shots/principal-0.9.png)

**Comment by monsta** [comment] 2016-03-02 13:55
Duplicate of as https://github.com/mate-desktop/caja/issues/241, see also https://github.com/mate-desktop/caja/issues/511 for a patch for that eiciel tool.

**Closed by monsta** 2016-03-02 13:55 UTC
Labels: feature request
