### ISSUE TITLE
Taskbar "launch notifications" are broken in spatial mode

### ISSUE THREAD

**Issue by Exalm** [mate-desktop/caja#175] opened 2013-09-28 15:40 UTC
They do not disappear after the window is created.
An example: Click the trash on panel, and it will be like:
[ Trash               ][ Opening /       ]
Caja 1.6.1, Ubuntu 13.10.  The issue is not present in Caja 1.4.0.
The bug is not present with default browser mode as well.
##

**Comment by flexiondotorg** [comment] 2017-01-17 19:02
I can't reproduce this in Ubuntu MATE 17.04 with MATE 1.17.

**Comment by raveit65** [comment] 2017-04-16 11:03
ok, closing as no respond from reporter and not reproducible any more with 17.04.

**Closed by raveit65** 2017-04-16 11:03 UTC
Labels: unconfirmed

**Comment by Exalm** [comment] 2017-04-16 11:32
Yes, it seems to has been fixed at some point.
