### ISSUE TITLE
[abrt] mate-file-manager-1.6.3-0.10.gitbf47018.fc20: magazine_cache_trim: Process /usr/bin/caja was killed by signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by brianjmurrell** [mate-desktop/caja#302] opened 2014-07-29 13:34 UTC
Per the downstream [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1035031) the following segfault has been discovered:

```
Truncated backtrace:
Thread no. 1 (10 frames)
 #0 magazine_cache_trim at gslice.c:655
 #1 magazine_cache_push_magazine at gslice.c:716
 #2 thread_memory_magazine2_unload at gslice.c:815
 #3 g_slice_free1 at gslice.c:1106
 #4 g_type_free_instance at gtype.c:1938
 #5 gtk_container_destroy at gtkcontainer.c:1073
 #10 gtk_object_dispose at gtkobject.c:421
 #12 gtk_toolbar_forall at gtktoolbar.c:2529
 #13 gtk_container_destroy at gtkcontainer.c:1073
 #18 gtk_object_dispose at gtkobject.c:421
```

Much more detail (including full backtrace, etc.) can be found at the above URL.

**Comment by monsta** [comment] 2015-01-03 11:38
Unfortunately, that bug report is more than a year old now, and MATE 1.6 isn't supported anymore. Were there similar crashes with 1.8 as well?

**Comment by NiceandGently** [comment] 2015-01-10 21:17
fedora report has reached EOL an will be closed automaticly in 4 weeks.

**Comment by monsta** [comment] 2015-01-11 19:37
Ok, if we don't get the report on 1.8.x this issue can be closed I guess.

**Comment by monsta** [comment] 2015-03-18 13:16
@brianjmurrell: I think you can close this now (unless there are similar downstream reports about 1.8).

**Comment by NiceandGently** [comment] 2015-03-18 14:24
@monsta 
maybe this ones...not shure
https://bugzilla.redhat.com/show_bug.cgi?id=1174006
https://bugzilla.redhat.com/show_bug.cgi?id=1097439

**Comment by monsta** [comment] 2015-03-18 14:46
Hmm, the trace is a bit different there...

**Comment by NiceandGently** [comment] 2015-03-18 15:24
OK, than 
@brianjmurrell
please close

**Comment by monsta** [comment] 2015-03-18 18:12
Anyway, the traces in all three reports show that the problem is somewhere in GLib or GTK+ - there's no MATE code mentioned in the backtraces.

**Comment by NiceandGently** [comment] 2015-03-18 18:35
:) same as ever...

**Comment by monsta** [comment] 2015-03-22 11:24
Yeah, it's surely in the lower levels. Here's the report about Pluma crashing with the trace similar to https://bugzilla.redhat.com/show_bug.cgi?id=1097439:

https://bugs.launchpad.net/bugs/1434155

**Closed** 2015-05-19 14:28 UTC
Labels: unconfirmed
