### ISSUE TITLE
Ubuntu MATE: Folder color not working in list view

### ISSUE THREAD

**Issue by ZrN-kAyDqY** [mate-desktop/caja#410] opened 2015-04-28 21:58 UTC
For Ubuntu MATE 15.04 -- The folder color is not able to be changed in "List View" (but it does work in icon and compact views).

System: Kernel: 3.19.0-15-generic x86_64 (64 bit gcc: 4.9.2)
  Desktop: MATE 1.8.2 (Gtk 3.14.12-0ubuntu2) Distro: Ubuntu 15.04 vivid
  Quad core AMD Phenom II X4 965 (-MCP-) 
  Graphics: Card: Advanced Micro Devices [AMD/ATI] Cedar [Radeon HD 5000/6000/7350/8350 
  Display Server: X.Org 1.17.1 drivers: ati,radeon (unloaded: fbdev,vesa) Resolution: 1920x1200@60.0hz
  GLX Renderer: Gallium 0.4 on AMD CEDAR GLX Version: 3.0 Mesa 10.5.2 Direct Rendering: Yes

caja: Installed: 1.8.2-3; Candidate: 1.8.2-3
          Version table: **\* 1.8.2-3 0
          500 http://us.archive.ubuntu.com/ubuntu/ vivid/universe amd64 Packages
##

**Comment by stoermerjp** [comment] 2015-06-02 21:49
i can reproduce in Linux Mint 17.1 w/ Caja 1.8.2
http://snag.gy/tKXrJ.jpg <-- "List View" mode with no folder icon color for /tmp

**Comment by ZrN-kAyDqY** [comment] 2015-06-08 01:59
That's true, when I used Mint, saw it there as well.

**Comment by monsta** [comment] 2016-01-26 18:47
I recall there were fixes for this in recent Mint versions... and as for Ubuntu, 15.04 is going EOL [in a week](https://lists.ubuntu.com/archives/ubuntu-announce/2016-January/000203.html). Is it reproducible in 15.10 or 16.04?

**Comment by flexiondotorg** [comment] 2016-01-27 20:16
Still not working in 16.04.

**Comment by monsta** [comment] 2016-03-18 17:42
@alexandervdm: can you please look at this issue?

**Comment by flexiondotorg** [comment] 2017-01-17 20:34
This is reproducible in Ubuntu MATE 17.04 with MATE 1.17.

**Comment by lukefromdc** [comment] 2017-01-17 20:46
This could get ugly with GTK 3.22 and the changes it needed to icon views to handle the desktop

**Comment by monsta** [comment] 2017-01-20 09:19
In the icon and compact views it still works even with GTK+ 3.22. It's something in the list view, probably some needed metadata isn't being read from the folders.

**Comment by raveit65** [comment] 2017-04-16 11:27
I guess it's because listview is a GtkTreeview.

**Comment by monsta** [comment] 2017-04-19 17:59
Somehow it works in the list view in Nemo, at least I heard so. Maybe it even had been fixed in Nautilus before the fork (version 3.2 or so I think). My searching for relevant commits didn't bring any results, maybe you guys would be more lucky. :slightly_smiling_face:

**Comment by raveit65** [comment] 2017-04-19 18:20
> My searching for relevant commits didn't bring any results, maybe you guys would be more lucky.

No wonder, Backgrounds&Emblems gui was dropped very early before 3.0.0

**Comment by monsta** [comment] 2017-04-19 19:12
I decided to give it one more try, and I think I've found the commit. At least the fix works in my Mint 18.1 with Mint's version of folder-color extension. Please test https://github.com/mate-desktop/caja/pull/765.

**Closed** 2017-04-20 09:55 UTC
Labels: confirmed

**Comment by jpegjpeg** [comment] 2017-05-04 08:45
Dear Developers.

I know this Bug might seem as a small issue to you. Well, let me explain why it isn't:

List view is one of the most used by my colleagues and me when having a lot of elements in a folder. We are musicians and coming from Mac world, so we try to adapt and get to know the open source community.

Colors help to make our everyday-work easier. You find important things faster, you need to invest less time. Not only I, but some of my friends also contributed (though small, but still) financially to some of the programms.

I know, that you don't live from this, and there might be more important things in real live. But please, things like this make it easier for people comming from commercial software universe to get along.

And everybody that doesn't have to pay 2500€ for a new macbook, is more willing to donate 20-50 Euros to the project.

keep the good work going! thank you for your work so far!

**Comment by raveit65** [comment] 2017-05-04 08:51
As you can see it is fixed from our side.
Maybe the commit isn't in ubuntu builds?
Maybe you don't use the folder-color extension.

**Comment by jpegjpeg** [comment] 2017-05-04 11:19
I use ubuntu Mate 16.04, already searched synaptic, I have the folder color extension installed. as I said, I cannot see the colors in "list view", which would help a lot! cheers, thank you for your reply.

**Comment by raveit65** [comment] 2017-05-04 11:31
Than you need to file out a report at your distro and ask maintainer to apply the fix for 16.04.
But we are upstream and we have no influence about downstream ubuntu ;-)

**Comment by jpegjpeg** [comment] 2017-05-04 12:12
ok, can I ask you one more question? - where Can I open such a thread or find a report? -  I searched here already far too long and I have to admit, I am just a user (;

**Comment by monsta** [comment] 2017-05-04 17:40
https://bugs.launchpad.net/bugs/1442681
