### ISSUE TITLE
GTK quickfind closes each key press

### ISSUE THREAD

**Issue by JoshDreamland** [mate-desktop/caja#152] opened 2013-08-16 19:01 UTC
The little box that appears when you start typing a filename is destroyed and cleared every time I press a new key. So if I keep typing, it won't keep searching for files matching the string I've typed, but will instead move on to files matching the latest substring. If I type fast I can cram in three to five letters before this behavior happens; it's not very regular, just annoying. After whatever delay it is, it begins a new search. The box is consistently destroyed after the second letter is typed; it's just not cleared until that delay expires. Probably the delay before clear is an intended behavior, but the box being destroyed is a result of it losing focus as a new file is selected.

**Comment by NiceandGently** [comment] 2015-05-19 14:43
Is the issue still exists?
Caja version?
Distro?

**Comment by monsta** [comment] 2015-06-11 11:00
I can't reproduce it in 1.8. Since there's no reply for 23 days and the issue has "unconfirmed" label, I'm closing it.

**Closed by monsta** 2015-06-11 11:00 UTC
Labels: unconfirmed
