### ISSUE TITLE
Wrong text color in Caja, Mint MATE 17.1/2

### ISSUE THREAD

**Issue by ingeva** [mate-desktop/caja#438] opened 2015-07-13 06:56 UTC
From LinuxMint MATE 17.1, caja sometimes switches text color to very light grey, making it impossible to read. I'm using a standard Mint-X theme with slightly changed colors but it's not possible to change foreground/background color in window. I've tried to install other themes but haven't been able to make it work. Instructions don't match reality. If I change background or text color in theme, text reappears, only to disappear again shortly after.
Clicking on the right side after F3 makes text reappear, but it tends to occur again very soon. I've tried Nautilus and Nemo but they lack caja's nice F3 feature.
Screenshot follows.
![screenshot-phpbb](https://cloud.githubusercontent.com/assets/1525307/8644048/cd48e680-293b-11e5-9f95-a7db5e411973.png)

**Comment by flexiondotorg** [comment] 2015-07-13 07:10
Please report this issue to Linux Mint, the MATE team do no maintain the Mint-X theme.

**Comment by ingeva** [comment] 2015-07-13 07:17
I did. They told me to report it here. I believe it's a caja problem, not a theme problem, but I need confirmation. They could not reproduce the error, and I can't NOT reproduce the error.

**Comment by flexiondotorg** [comment] 2015-07-13 07:21
I've never encountered this issue on Arch Linux or on Ubuntu MATE. If you can provide steps to reproduce the issue using the Menta theme then we can reopen this issue and investigate ☺

**Comment by ingeva** [comment] 2015-07-13 07:36
As I mentioned, I believe it's a caja problem, not a theme problem, but I'm open to anything as long as I can make it work. It's too annoying as it is.
There are several directories in all themes. Which one do I place in ~/.themes?

**Comment by ingeva** [comment] 2015-07-13 08:02
For now I have switched to the Mint-X Blue theme, and just changed the window border, no colors. I haven't seen the error yet. If it doesn't happen again I'll just stick to this theme. As long as no one else reports the error, we'll assume it's a local problem only. For me the theme is unimportant. I just want a working system with good colors (contrast) and visible text. :)

**Comment by infirit** [comment] 2015-07-13 08:32
Please also experiment with the default mental theme.

**Comment by ingeva** [comment] 2015-07-13 09:19
The default theme is Mint-X and its variants, and I've tried to install other themes with no luck.

**Comment by iugostudio** [comment] 2015-11-18 13:03
I have similar problem. 
![lightgrey_309](https://cloud.githubusercontent.com/assets/14885632/11241690/8751967a-8e05-11e5-8a9a-e1021b270f70.png)

**Comment by ingeva** [comment] 2015-11-18 18:21
I'm happy to see that at least one other user has the same problem - or shall we say a similar one? Because for me it only happens with compact layout! I've tried all available (standard)  themes, and I have still not managed to install any other because they are not presented in a form that I can use with my limited knowledge.
I'm still using Mint MATE, because it's the only sensible interface I've found in linux systems. I've learnt to live with the disappearing text, because I can just press F3 and switch to the adjacent window. However it's still a nuisance.
I can't use Cinnamon because it makes no sense to me. The same of course with Ubuntu's Unity, although it's been at least 3 years since I changed to Mint so I can't say for sure.

**Comment by iugostudio** [comment] 2015-11-18 19:35
For me F3 help too,  thank for this hint. Previously this bug was appear somethimes in some directories when in other not. But newly It becomes permanent in all directories. I change theme to Mint-X Blue too and now do not see that bug. Hopefully it will no longer appear.

**Comment by ingeva** [comment] 2015-11-19 07:16
I'm using Mint-X. No change.

**Comment by monsta** [comment] 2015-11-19 13:01
> I'm using a standard Mint-X theme with slightly changed colors

I can't reproduce that - can you please try *unmodified* theme?

> I've tried to install other themes but haven't been able to make it work.

There's nothing really needed to "make it work". Install & setup in Mint is trivial:

- ```apt install mate-themes```
- Control Center -> Appearance -> choose the theme

That's it - now you can try to reproduce the issue in Menta and other new themes :smile:

**Comment by ingeva** [comment] 2015-11-19 19:16
Modified OR unmodifed Mint-X or any other Mint theme:  Same thing occurs.
Modified OR unmodified Menta theme: Same thing occurs.

I have never thought that this is a theme issue, and I still don't. I have every reason to believe that it's either Caja itself (it doesn't occur with any other program, not even Nemo or Nautilus) or with some other system change from 17.0 to 17.1.

BTW, thanks for informing me how to install the mate themes. All I've tried before is control Center -> Appearence -> Theme / Get more themes online -- which has only left me with more questions than answers. Not that I need them, evidently. :)

I'm still using Caja, mostly because of its ability to split the screen, and because of that feature there's a way to overcome the problem. But it's a nuisance, and the bug should be found and removed.

**Comment by clefebvre** [comment] 2015-11-24 09:59
I can't reproduce it either..

**Comment by ingeva** [comment] 2015-11-24 10:43
Well, I wish I could use Caja for more than 2 minutes without experiencing this bug. Nothing I have done to remove the bug, has worked, except going back to Mint 17.0, which is not something I want to do. After all, the advantages still overcome this nuisance. However, as soon as I have time I'll install 17.3 so I can see if that makes a difference.

**Comment by mariellama** [comment] 2015-11-24 17:17
I had the same problem in Mint MATE 17.1. I then updated to 17.2 and everything just works fine.
Best system ever :)

**Comment by nypaulie** [comment] 2015-12-05 20:33
I was fine with LMint 17 Qiana, but upgrading to Rafael and then to Rosa gave me that washed out icon text. I used the caja fix (Edit/Backgrounds and Emblems) found here: https://github.com/mate-desktop/caja/issues/81 and using a dark color made the white letters Pop!

**Comment by ingeva** [comment] 2015-12-09 19:39
I have tried "everything", including starting from the beginning, with a fresh installation of Mint 17.3 and a virgin home directory. No luck. Changing theme is only a temporary fix. Today I got a caja update, 1.12.1.1, which still shows as 1.12.0 in "Help, about". My hope was soon broken; a few times switching directories again gave its nearly white font on white background. I understand that if the background is dark, the font colour will also go dark. This a bad and very annoying bug, and I wish someone would address it soon. Again I'll remind the readers/developers that this did not happen until the 17.1 version. Is the 18.0 version coming in the near future?

**Comment by roman-gich** [comment] 2015-12-10 07:09
I've got the same issue...
![-89](https://cloud.githubusercontent.com/assets/13838461/11709086/3e909fa2-9f1d-11e5-93ce-ce25e9f1c239.png)

**Comment by monsta** [comment] 2015-12-10 12:18
How do you reproduce this issue? I've tried going back and forth between folders, in all three view modes - no luck.

I also suspect it might be related to video card and/or its drivers. Which video cards do you guys have?
And if you have some virtual machine like VirtualBox, could you please try to reproduce it there?

**Comment by monsta** [comment] 2015-12-10 12:24
> Modified OR unmodifed Mint-X or any other Mint theme: Same thing occurs.
Modified OR unmodified Menta theme: Same thing occurs.

Ok... to everyone who reported - do you guys also see it with other themes? Other than Mint-X I mean.

**Comment by alexandervdm** [comment] 2015-12-10 12:33
I can consistently reproduce this issue using caja 1.10.4 on Gentoo using themes like Ambiant-MATE and TraditionalOK:

1. Open folder in icon view
2. Switch to list view
3. Search for something
4. Results have wrong text colour

**Comment by roman-gich** [comment] 2015-12-10 13:01
It happens when in the "Controls" tab of any Mint-X theme other than Mint-X item has been chosen, other tabs don't affect it.

**Comment by ingeva** [comment] 2015-12-10 13:55
I have told you guys what I have done. I experience the same problem on all my 3 different computers; two of them are laptops, and they probably to not have the same graphics card. I have generated a "virgin" system with MATE 17.3, and have reproduced the problem before doing any modifications at all. I can't NOT reproduce the error, but if I try it tends to take more time! :)

**Comment by ingeva** [comment] 2015-12-18 06:16
It seems that I have found a solution!
Choice of background in caja didn't work before, but it does with the MATE 17.3 edition. I don't know about Cinnamon because I don't use it (Tried but hated it).
If you change the background color, the text and background will show with sufficient contrast to be readable. I have chosen white background because that's what I like best. The text will then show as black. If you choose a dark color as background, the text will be white. Similarly, if you choose a pattern background, you'll get a matching foreground color.
I see this as a temporary fix. The error lies somewhere else but I still don't believe it's in the theme because it should then appear in other programs as well.
What to do: In caja, choose Edit -> Backgrounds and Emblems. Choose the background you want, and drag it to the background of the program. Experiment with different backgrounds if you like. You may be surprised.

**Comment by roman-gich** [comment] 2015-12-18 08:11
I've chosen white background because I prefer this one too - no changes. The issue has been resolved by adding a new color "White2" (#FEFEFE). Thank you so much, @ingeva

**Comment by maazl** [comment] 2015-12-23 14:12
Interestingly the problem is also fixed by changing the color in the theme editor. Even if the value is reset to the previous value (white) one after that, the text color in Caja is still black.
Furthermore the themes that do not work claim that the GTK+ theme "Dust" is not installed. Probably this is the origin of the problem - a missing theme.

**Comment by raveit65** [comment] 2016-01-05 17:48
@monsta 
I found a way to reproduce the issue with every light theme.
1. select the root dir in caja browser.
2. open a second tab from menu
3. do step 2 again
Now you see in the third tab a light fg color on light bg.
This is a regression caused by https://github.com/mate-desktop/caja/pull/285
Reverting this commit fixes the issue for me.
Unfortunately the issue with the fg color for dark themes still exists.
I think this logic does not work for dark themes. 
https://github.com/mate-desktop/caja/blob/master/libcaja-private/caja-icon-container.c#L9437

**Comment by ingeva** [comment] 2016-01-06 05:49
For some reason different installations seem to give different results, although in all my computers caja behave the same way.
@raveit65, I don't need the menu, and I don't need to open more than the first new tab; Ctrl+T and a new tab opens, with invisible text. I don't have to navigate to the root either; what directory I choose is irrelevant. The bug appears EVERY time. The only way that seems to work permanently is to choose a background (In caja: Edit, Backgrounds and Emblems) - different from pure white, which evidently is the standard "no color".

**Comment by raveit65** [comment] 2016-01-06 13:17
@ingeva and others, can please test https://github.com/mate-desktop/caja/commit/61800829da41036da5719b0e39e6f015cbd75f9a
This fixes the issue here, tested in fedora with BlueMenta theme.
Btw. the default for Mate is not Mint-X :smile:

**Comment by monsta** [comment] 2016-01-06 14:58
@raveit65: cool, I've managed to reproduce it with your steps :smile:
And https://github.com/mate-desktop/caja/pull/495 fixes it for me. Theme used is Mint-X.

**Comment by raveit65** [comment] 2016-01-19 15:03
We have a regression again.
With last fix fg color does not change if a custom bg is choosen.

**Closed** 2016-01-19 15:05 UTC
Labels: unconfirmed

**Comment by monsta** [comment] 2016-03-25 07:59
Ok, Caja 1.12.4 with the fix is in Mint 17.3 repos now.
