### ISSUE TITLE
Segmentation Fault - assertion 'CAJA_IS_DIRECTORY (directory)' failed

### ISSUE THREAD

**Issue by hallzy** [mate-desktop/caja#1529] opened 2021-05-18 02:23 UTC
#### Expected behaviour

Running caja should open caja

#### Actual behaviour

Running caja throws a segmentation fault with the following output in terminal:

```bash
$ caja
Initializing caja-open-terminal extension

** (caja:3858448): CRITICAL **: 19:14:05.704: caja_directory_file_monitor_add: assertion 'CAJA_IS_DIRECTORY (directory)' failed
sys:1: Warning: invalid (NULL) pointer instance
sys:1: Warning: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
RuntimeError: object at 0x7f464ec0e540 of type RenameMenu is not initialized
RuntimeError: object at 0x7f464e60b880 of type FolderColorMenu is not initialized

** (caja:3858448): CRITICAL **: 19:14:06.285: caja_directory_get_uri: assertion 'CAJA_IS_DIRECTORY (directory)' failed
Segmentation fault (core dumped)
```

No window is shown.

#### Steps to reproduce the behaviour

Run caja.

#### MATE general version

1.24.0

#### Package version

1.24.0

#### Linux Distribution

Ubuntu Mate 20.04.2 LTS

#### Additional Information

I have had this problem ever since upgrading from 18.04 LTS. Running caja with sudo does not produce the segfault.

**Comment by lukefromdc** [comment] 2021-05-18 05:50
I cannot duplicate that with caja and the caja-open-terminal extension. Running `sudo caja`  (may have to run `xhost +local:` first to allow a sudo connection to the running X session on newer systems) from a mate session (caja already running, GtkApplication holds it to one instance so running `caja` just returns) I get this:

```
luke@ubuntu:~$ sudo caja
[sudo] password for luke: 
Initializing caja-sendto extension
Initializing caja-xattr-tags extension
Initializing caja-share extension
Initializing caja-open-terminal extension
Initializing caja-image-converter extension
Initializing caja-wallpaper extension

```
That said,. I've seen a lot of similar errors (usually not past the warning level) while doing a variety of different things with caja. These sort of things look like race conditions, where something is not done being set up before it is used, or is destroyed too quickly for its last use to finish with ith.

**Comment by hallzy** [comment] 2021-05-18 06:05
hmm.

Just to be clear, my output at the top is without sudo. I can only open caja if I run it with sudo, and when i do that I get this:

```bash
$ sudo caja
[sudo] password for steven:
Initializing caja-open-terminal extension
RuntimeError: object at 0x7fec95243180 of type RenameMenu is not initialized
RuntimeError: object at 0x7fec94b1e180 of type FolderColorMenu is not initialized
```

I never really paid attention to what it said when I did this because it loaded, but maybe those runtime errors might be useful (These are actually also in the error at the top of this issue as well, so not unique to running with sudo)

**Comment by lukefromdc** [comment] 2021-05-18 06:29
Are you running caja from a mate-session or standalone in another desktop environment? I was just using sudo to invoke a new instance of caja (as root is a different user)

**Comment by hallzy** [comment] 2021-05-18 06:45
So...

The short answer to your question is standalone in another desktop environment, but I am running Ubuntu Mate. I just decided to install a window manager and use that after a little while.

The long answer for full context is I initially installed Ubuntu 16.04 LTS on this computer back when that was the latest version and I used it as is for a while. Then I started using the DWM window manager still using ubuntu mate 16.04. Caja worked fine before and after DWM.

I then upgraded to Ubuntu Mate 18.04 LTS, still using DWM. Caja worked fine after this upgrade.

I then upgraded to Ubuntu Mate 20.04 LTS, still using DWM, and that is when Caja broke. Now, I don't remember if caja worked fine at first and it broke later, or if it was broken straight after the upgrade. I'd like to think that I would have noticed that breaking right away, but I can't be 100% sure of that. I tend to use the terminal for most of my daily use and only use a file manager like caja once in a while.

**Comment by lukefromdc** [comment] 2021-05-18 06:51
OK, so with caja not as part of your session, you are starting that from terminal. This should work and give the exact same thing I get with sudo caja in a terminal so far as startup messages go if you are using the dame extensions. This sounds like you got an incomplete update, and one or more caja packages, mate-desktop, or something else it depends on didn't update propertly. Breaking things on a distro update is a known hassle probably not just with ubuntu but probably most distros.

Also could be an issue with Ubuntu's build, a race condition requiring a machine exactly as fast as yours, or something else entirely

**Comment by hallzy** [comment] 2021-05-18 16:13
I did try an `apt reinstall` on all the caja packages I have installed but that didn't fix anything. I can have a look to see if there are any mate ones maybe after I get off work.

> a race condition requiring a machine exactly as fast as yours

Or in my case, slow lol. My computer is pushing 10 years old. It is definitely not fast by today's standards. Although it isn't really slow either.

**Comment by lukefromdc** [comment] 2021-05-19 05:33
Please do post a report on Ubuntu's bug reporting system in case this is Ubuntu-specific. I can't do much on this myself, as I don't get the crash. If you can get a backtrace it might help. Install the caja debugging symbols, then run
`gdb caja`
and type
`run`
you should get the crash.
Then run 
`thread apply all bt full`
and copy the resulting text from terminal into a text file. You can do it one section at a time, from the pager in terminal so as to avoid terminal bugs that don't give you all the text on "select all" from the menu.  If you do get all the text at once, great: the job is simpler.
Examine that text and make sure you didn't get anything sensitive in it,then compress the file into a .gz file and upload it here.

**Comment by hallzy** [comment] 2021-05-19 06:03
Took a bit of googling to install the debug symbols. I didn't realize there was a separate source for debugging symbols, but that is good to know.

I have attached the file with the full output starting from from the gdb caja command just so everything is there. Hopefully something there is useful

[caja-dbg.txt.gz](https://github.com/mate-desktop/caja/files/6506221/caja-dbg.txt.gz)

**Comment by lukefromdc** [comment] 2021-05-19 09:13
OK, you are getting 

```
** (caja:205521): CRITICAL **: 22:54:50.401: caja_directory_get_uri: assertion 'CAJA_IS_DIRECTORY (directory)' failed

Thread 1 "caja" received signal SIGSEGV, Segmentation fault.
0x00005555555f9b3b in directory_belongs_in_scripts_menu (uri=0x0) at fm-directory-view.c:5592
5592    fm-directory-view.c: No such file or directory.
(ins)(gdb)
```

```
static gboolean
directory_belongs_in_scripts_menu (const char *uri)
{
	int num_levels;
	int i;

	if (!eel_str_has_prefix (uri, scripts_directory_uri)) {
		return FALSE;
	}

	num_levels = 0;
	for (i = scripts_directory_uri_length; uri[i] != '\0'; i++) {
		if (uri[i] == '/') {
			num_levels++;
		}
	}

	if (num_levels > MAX_MENU_LEVELS) {
		return FALSE;
	}

	return TRUE;
}
```
This is erroring out at 
`for (i = scripts_directory_uri_length; uri[i] != '\0'; i++) {`

I cannot fix this as I cannot duplicate it, but it looks like directory_belongs_in_scripts_menu() is getting called with an invalid uri, possibly NULL. It can be called from only two places:

line` 5645` in 
`update_directory_in_scripts_menu()`

or at 
line` 5704`
in
`update_scripts_menu `
both of these lines are
`		if (!directory_belongs_in_scripts_menu (uri)) {`
and one of these functions is reaching that point with a bad uri

**Comment by lukefromdc** [comment] 2021-05-19 09:30
My guess is one of your extensions is crashing in some way or otherwise has a problem. I am presuming the scripts menu is the part of the right-click menu where your extensions are listed. You are getting two warnings in terminal right after initializing the caja-open-terminal extension, one related to a menu item I don't get for changing folder colors, the rename menu item appears in a different part of the right-click menu.

Do you have an extension installed related to renaming directories (say to bulk rename them)? Do you have an extension for changing folder colors installed?

If so, try disabling (in caja's preferences >extensions menu) or uninstalling both of them, then starting caja again and seeing if this problem stops. If it does not, also disable the open terminal extension and try again. If the problem stops at either of these points, then try re-enabling these extensions one at a time and launching caja. If the segfault returns, you have found a bad extension, probably needing to be rebuilt for your caja version. 

If any of these extensions are leftover versions from 18.04, that might be your problem. I recall some changes (forget what they were) in caja and in the extensions in 2019 that broke backwards compatability.

**Comment by lukefromdc** [comment] 2021-05-19 18:52
Ideally that sort of thing should be NULL checked, but as this is resolved for you and nobody else has had this problem we can now close this. No doubt there are many other such places in caja, the rest of MATE, and all other DE's where such things should be checked-and also keep in mind the more checks you run, the more CPU intensive a program becoomes

**Closed by lukefromdc** 2021-05-19 18:52 UTC

**Comment by tycho-kirchner** [comment] 2022-12-18 21:59
Ouch, I just lost an hour trying to reproduce, why caja would segfault because of _this_ issue (Debian Bullseye, caja v1.24.0). I would appreciate a small check, whether config files refer to broken symlinks. Caja is running all the time anyway, so I suspect the startup penalty would be small 🤞
