### ISSUE TITLE
MATE 1.16 on openSUSE Leap 42.1

### ISSUE THREAD

**Issue by sidro** [mate-desktop/caja#657] opened 2016-10-13 20:24 UTC
Caja freeze if I select properties for a pdf file.
##

**Comment by kn00tcn** [comment] 2016-10-26 09:47
do you have a caja extension for generating previews of pdf?

**Comment by monsta** [comment] 2016-11-25 14:11
I presume it's 1.16, not 1.6 :smile:
However, we can't do anything about it due to lack of info:

- which GTK+ version is used, 2 or 3
- if GTK+3, which version of it
- link to sample PDF file for us to test

Closing, will reopen if necessary info is added.

**Comment by cremerr** [comment] 2017-02-14 11:34
We are using opensuse 42.1 with same problem.
Workaround is to disable Atril extension in Caja.

**Comment by monsta** [comment] 2017-02-14 12:09
@XRevan86: can you reproduce this in OpenSUSE?

**Comment by cremerr** [comment] 2017-02-14 12:30
This behavior is the same on more than 8 opensuse 42.1 systems with Mate desktop.
```
cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:42.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"

```

**Comment by lukefromdc** [comment] 2017-02-14 18:25
This could be an issue with caja or an issue with Atril, from which the extension comes

**Comment by monsta** [comment] 2017-02-15 13:32
It might be something distro-specific - I've never seen such issue in Debian/Ubuntu/Mint.

**Comment by willysr** [comment] 2017-02-15 14:21
is it possible to post the PDF file somewhere public so we can test them?

**Comment by XRevan86** [comment] 2017-03-05 16:50
Yes, it is distro-specific as there was a mistake: Atril was built with Gtk3 which created issues with the Caja extension.

**Closed by XRevan86** 2017-03-05 16:50 UTC
Labels: unconfirmed
